import { Router } from "express";

import areas_interes from "./areas_interes_routes.js";
import cargos_empleados from "./cargos_empleados_routes.js";
import cargos_niveles from "./cargos_niveles_routes.js";
import cargos from "./cargos_routes.js";
import contactos_emergencia from "./contactos_emergencia_routes.js";
import curriculos from "./curriculos_routes.js";
import datos_bancarios from "./datos_bancarios_routes.js";
import departamentos from "./departamentos_routes.js";
import direcciones from "./direcciones_routes.js";
import documentos_empleados from "./documentos_empleados_routes.js";
import empleados from "./empleados_routes.js";
import empresas from "./empresas_routes.js";
import estados from "./estados_routes.js";
import etnias from "./etnias_routes.js";
import experiencias from "./experiencias_routes.js";
import fichas_ingresos from "./fichas_ingresos_routes.js";
import idiomas from "./idiomas_routes.js";
import menus from "./menus_routes.js";
import movimientos from "./movimientos_routes.js";
import municipios from "./municipios_routes.js";
import paises from "./paises_routes.js";
import parroquias from "./parroquias_routes.js";
import preguntas_kostick from "./preguntas_kostick_routes.js";
import pruebas_empleados from "./pruebas_empleados_routes.js";
import referencias_personales from "./referencias_personales_routes.js";
import respuestas_kostick from "./respuestas_kostick_routes.js";
import roles_menus from "./roles_menus_routes.js";
import roles from "./roles_routes.js";
import salud from "./salud_routes.js";
import sedes from "./sedes_routes.js";
import sesiones from "./sesiones_routes.js";
import sugerencias_pred from "./sugerencias_pred_routes.js";
import sugerencias from "./sugerencias_routes.js";
import clases_movimientos from "./clases_movimientos_routes.js";
import tipos_sugerencias from "./tipos_sugerencias_routes.js";
import titulos_obtenidos from "./titulos_obtenidos_routes.js";
import vacantes from "./vacantes_routes.js";

const router = Router();

router.use("/tthh/areas_interes", areas_interes);
router.use("/tthh/cargos_empleados", cargos_empleados);
router.use("/tthh/cargos_niveles", cargos_niveles);
router.use("/tthh/cargos", cargos);
router.use("/tthh/contactos_emergencia", contactos_emergencia);
router.use("/tthh/curriculos", curriculos);
router.use("/tthh/datos_bancarios", datos_bancarios);
router.use("/tthh/departamentos", departamentos);
router.use("/tthh/direcciones", direcciones);
router.use("/tthh/documentos_empleados", documentos_empleados);
router.use("/tthh/empleados", empleados);
router.use("/tthh/empresas", empresas);
router.use("/tthh/estados", estados);
router.use("/tthh/etnias", etnias);
router.use("/tthh/experiencias", experiencias);
router.use("/tthh/fichas_ingresos", fichas_ingresos);
router.use("/tthh/idiomas", idiomas);
router.use("/tthh/menus", menus);
router.use("/tthh/movimientos", movimientos);
router.use("/tthh/municipios", municipios);
router.use("/tthh/paises", paises);
router.use("/tthh/parroquias", parroquias);
router.use("/tthh/preguntas_kostick", preguntas_kostick);
router.use("/tthh/pruebas_empleados", pruebas_empleados);
router.use("/tthh/referencias_personales", referencias_personales);
router.use("/tthh/respuestas_kostick", respuestas_kostick);
router.use("/tthh/roles_menus", roles_menus);
router.use("/tthh/roles", roles);
router.use("/tthh/salud", salud);
router.use("/tthh/sedes", sedes);
router.use("/tthh/sesiones", sesiones);
router.use("/tthh/sugerencias_pred", sugerencias_pred);
router.use("/tthh/sugerencias", sugerencias);
router.use("/tthh/clases_movimientos", clases_movimientos);
router.use("/tthh/tipos_sugerencias", tipos_sugerencias);
router.use("/tthh/titulos_obtenidos", titulos_obtenidos);
router.use("/tthh/vacantes", vacantes);

export default router;
