const ciudades = [
  {
    estado: "Zulia",
    ciudades: [
      "Ancón De Iturre",
      "Bachaquero",
      "Barrancas",
      "Bobures",
      "Cabimas",
      "Castilletes",
      "Ceuta",
      "Ciudad Ojeda",
      "Curazaito",
      "El Consejo De Ciruma",
      "El Danto",
      "El Guanábano",
      "El Güere",
      "El Mecocal",
      "El Mene",
      "El Menito",
      "El Toro",
      "El Venado",
      "Encontrados",
      "Gibraltar",
      "La Pica Pica",
      "La Plata",
      "La Ribera",
      "La Vaca",
      "Lagunillas",
      "Los Puertos De Altagracia",
      "Machiques",
      "Maracaibo",
      "Mene Grande",
      "Monte Pío",
      "Paraguaipoa",
      "Pueblo Nuevo - El Chivo",
      "Quisiro",
      "Sabaneta De Palmas",
      "San Carlos",
      "San Francisco",
      "San Isidro",
      "San Joaquín De La Vega",
      "San Rafael De El Moján",
      "San Timoteo",
      "Santa Bárbara",
      "Santa Rita",
      "Sinamaica",
      "Tía Juana",
      "Turiacas",
      "Villa Del Rosario",
    ],
  },
];

module.exports = {
  ciudades,
};
