const parroquias = [
  {
    pais: "Venezuela",
    estado: "Amazonas",
    municipios: [
      {
        municipio: "Autónomo Alto Orinoco",
        parroquias: [
          "Alto Orinoco",
          "Huachamacare",
          "La Esmeralda - Alto Orinoco",
          "Marawaka",
          "Mavaca",
          "Sierra Parima",
        ],
      },
      {
        municipio: "Autónomo Atabapo",
        parroquias: ["Caname", "San Fernando De Atabapo", "Ucata", "Yapacana"],
      },
      {
        municipio: "Autónomo Atures",
        parroquias: [
          "Fernando Girón Tovar",
          "Luis Alberto Gómez",
          "Parhueña",
          "Platanillal",
        ],
      },
      {
        municipio: "Autónomo Autana",
        parroquias: [
          "Guayapo",
          "Isla Ratón",
          "Munduapo",
          "Samariapo",
          "Sipapo",
        ],
      },
      {
        municipio: "Autónomo Manapiare",
        parroquias: [
          "Alto Ventuari",
          "Bajo Ventuari",
          "Medio Ventuari",
          "San Juan De Manapiare",
        ],
      },
      {
        municipio: "Autónomo Maroa",
        parroquias: ["Comunidad", "Maroa", "Victorino"],
      },
      {
        municipio: "Autónomo Río Negro",
        parroquias: [
          "Casiquiare",
          "Cocuy",
          "San Carlos De Río Negro",
          "Solano",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Anzoátegui",
    municipios: [
      {
        municipio: "Anaco",
        parroquias: ["Anaco", "Buena Vista", "San Joaquín"],
      },
      { municipio: "Aragua", parroquias: ["Aragua", "Cachipo"] },
      {
        municipio: "Diego Bautista Urbaneja",
        parroquias: ["El Morro", "Lecherías"],
      },
      {
        municipio: "Fernando De Peñalver",
        parroquias: [
          "Puerto Píritu - Fernando De Peñalver",
          "San Miguel",
          "Sucre",
        ],
      },
      {
        municipio: "Francisco De Miranda",
        parroquias: [
          "Atapirire",
          "Boca Del Pao",
          "El Pao",
          "Pariaguán - Francisco De Miranda",
        ],
      },
      {
        municipio: "Francisco Del Carmen Carvajal",
        parroquias: ["Santa Bárbara", "Valle De Guanape"],
      },
      { municipio: "Guanta", parroquias: ["Chorrerón", "Guanta"] },
      {
        municipio: "Independencia",
        parroquias: ["La Soledad - Independencia", "Mamo"],
      },
      {
        municipio: "José Gregorio Monagas",
        parroquias: [
          "Mapire - José Gregorio Monagas",
          "Piar",
          "San Diego De Cabrutica",
          "Santa Clara",
          "Uverito",
          "Zuata",
        ],
      },
      {
        municipio: "Juan Antonio Sotillo",
        parroquias: ["Pozuelos", "Puerto La Cruz"],
      },
      { municipio: "Juan Manuel Cajigal", parroquias: ["Onoto", "San Pablo"] },
      {
        municipio: "Libertad",
        parroquias: ["El Carito", "San Mateo - Libertad", "Santa Inés"],
      },
      {
        municipio: "Manuel Ezequiel Bruzual",
        parroquias: ["Clarines", "Guanape", "Sabana De Uchire"],
      },
      {
        municipio: "Pedro María Freites",
        parroquias: [
          "Cantaura - Pedro María Freites",
          "Libertador",
          "Santa Rosa",
          "Urica",
        ],
      },
      { municipio: "Píritu", parroquias: ["Píritu", "San Francisco"] },
      { municipio: "San José De Guanipa", parroquias: ["San José De Guanipa"] },
      {
        municipio: "San Juan De Capistrano",
        parroquias: ["Boca De Chávez", "Boca Uchire"],
      },
      { municipio: "Santa Ana", parroquias: ["Pueblo Nuevo", "Santa Ana"] },
      {
        municipio: "Simón Bolívar",
        parroquias: [
          "Bergantin",
          "Caigua",
          "El Carmen",
          "El Pilar",
          "Naricual",
          "San Cristobal",
        ],
      },
      {
        municipio: "Simón Rodríguez",
        parroquias: ["Edmundo Barrios", "Miguel Otero Silva"],
      },
      {
        municipio: "Sir Arthur Mc Gregor",
        parroquias: ["El Chaparro", "Tomás Alfaro Calatrava"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Apure",
    municipios: [
      {
        municipio: "Achaguas",
        parroquias: [
          "Achaguas",
          "Apurito",
          "El Yagual",
          "Guachara",
          "Mucuritas",
          "Queseras Del Medio",
        ],
      },
      { municipio: "Biruaca", parroquias: ["Biruaca"] },
      {
        municipio: "Muñoz",
        parroquias: [
          "Bruzual",
          "Mantecal",
          "Quintero",
          "Rincón Hondo",
          "San Vicente",
        ],
      },
      {
        municipio: "Páez",
        parroquias: [
          "Aramendi",
          "El Amparo",
          "Guasdualito",
          "San Camilo",
          "Urdaneta",
        ],
      },
      {
        municipio: "Pedro Camejo",
        parroquias: ["Codazzi", "Cunaviche", "San Juan De Payara"],
      },
      { municipio: "Rómulo Gallegos", parroquias: ["Elorza", "La Trinidad"] },
      {
        municipio: "San Fernando",
        parroquias: [
          "El Recreo",
          "Peñalver",
          "San Fernando",
          "San Rafael De Atamaica",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Aragua",
    municipios: [
      { municipio: "Bolívar", parroquias: ["San Mateo - Bolívar"] },
      { municipio: "Camatagua", parroquias: ["Camatagua", "Carmen De Cura"] },
      {
        municipio: "Francisco Linares Alcántara",
        parroquias: [
          "Francisco De Miranda",
          "Monseñor Feliciano González - Paraparal",
          "Santa Rita - Francisco Linares Alcántara",
        ],
      },
      {
        municipio: "Girardot",
        parroquias: [
          "Andrés Eloy Blanco",
          "Choroní",
          "Joaquín Crespo",
          "José Casanova Godoy",
          "Las Delicias",
          "Los Tacariguas",
          "Madre María De San José",
          "Pedro José Ovalles",
        ],
      },
      { municipio: "José Ángel Lamas", parroquias: ["Capital Santa Cruz"] },
      {
        municipio: "José Félix Rivas",
        parroquias: [
          "Castor Nieves Ríos",
          "La Victoria - Juan Vicente Bolívar",
          "Las Guacamayas",
          "Pao De Zárate",
          "Zuata",
        ],
      },
      { municipio: "José Rafael Revenga", parroquias: ["El Consejo"] },
      {
        municipio: "Libertador",
        parroquias: ["Palo Negro - Libertador", "San Martín De Porres"],
      },
      {
        municipio: "Mario Briceño Iragorry",
        parroquias: ["Caña De Azúcar", "El Limón - Mario Briceño Iragorry"],
      },
      {
        municipio: "Ocumare De La Costa De Oro",
        parroquias: ["Ocumare De La Costa"],
      },
      {
        municipio: "San Casimiro",
        parroquias: [
          "Güiripa",
          "Ollas De Caramacate",
          "San Casimiro",
          "Valle Morín",
        ],
      },
      { municipio: "San Sebastián", parroquias: ["San Sebastián"] },
      {
        municipio: "Santiago Mariño",
        parroquias: [
          "Alfredo Pacheco Miranda",
          "Arévalo Aponte",
          "Chuao",
          "Samán De Güere",
          "Turmero - Santiago Mariño",
        ],
      },
      {
        municipio: "Santos Michelena",
        parroquias: ["Las Tejerías - Santos Michelena", "Tiara"],
      },
      { municipio: "Sucre", parroquias: ["Bella Vista", "Cagua - Sucre"] },
      { municipio: "Tovar", parroquias: ["Colonia Tovar"] },
      {
        municipio: "Urdaneta",
        parroquias: [
          "Barbacoas - Urdaneta",
          "Las Peñitas",
          "San Francisco De Cara",
          "Taguay",
        ],
      },
      {
        municipio: "Zamora",
        parroquias: [
          "Augusto Mijares",
          "Magdaleno",
          "San Francisco De Asís",
          "Valles De Tucutunemo - Los Bagres",
          "Villa De Cura - Zamora",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Barinas",
    municipios: [
      {
        municipio: "Alberto Arvelo Torrealba",
        parroquias: ["Rodríguez Domínguez", "Sabaneta"],
      },
      {
        municipio: "Andrés Eloy Blanco",
        parroquias: ["El Cantón", "Puerto Vivas", "Santa Cruz De Guacas"],
      },
      {
        municipio: "Antonio José De Sucre",
        parroquias: ["Andrés Bello", "Nicolás Pulido", "Ticoporo"],
      },
      {
        municipio: "Arismendi",
        parroquias: ["Arismendi", "Guadarrama", "La Unión", "San Antonio"],
      },
      {
        municipio: "Barinas",
        parroquias: [
          "Alfredo Arvelo Larriva",
          "Alto Barinas",
          "Barinas",
          "Corazón De Jesús",
          "Dominga Ortiz De Páez",
          "El Carmen",
          "Juan Antonio Rodríguez Domínguez",
          "Manuel Palacio Fajardo",
          "Ramón Ignacio Méndez",
          "Rómulo Betancourt",
          "San Silvestre",
          "Santa Inés",
          "Santa Lucía",
          "Torunos",
        ],
      },
      {
        municipio: "Bolívar",
        parroquias: ["Altamira", "Barinitas", "Calderas"],
      },
      {
        municipio: "Cruz Paredes",
        parroquias: ["Barrancas", "El Socorro", "Masparrito"],
      },
      {
        municipio: "Ezequiel Zamora",
        parroquias: [
          "José Ignacio Del Pumar",
          "Pedro Briceño Méndez",
          "Ramón Ignacio Méndez",
          "Santa Bárbara",
        ],
      },
      {
        municipio: "Obispos",
        parroquias: ["El Real", "La Luz", "Los Guasimitos", "Obispos"],
      },
      {
        municipio: "Pedraza",
        parroquias: [
          "Ciudad Bolivia",
          "Ignacio Briceño",
          "José Félix Ribas",
          "Páez",
        ],
      },
      {
        municipio: "Rojas",
        parroquias: [
          "Dolores",
          "Libertad",
          "Palacio Fajardo",
          "Santa Rosa",
          "Simón Rodríguez",
        ],
      },
      {
        municipio: "Sosa",
        parroquias: [
          "Ciudad De Nutrias",
          "El Regalo",
          "Puerto De Nutrias",
          "Santa Catalina",
          "Simón Bolívar",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Bolívar",
    municipios: [
      {
        municipio: "Bolivariano Angostura",
        parroquias: [
          "Barceloneta",
          "Ciudad Piar",
          "San Francisco",
          "Santa Bárbara",
        ],
      },
      {
        municipio: "Caroní",
        parroquias: [
          "5 De Julio",
          "Cachamay",
          "Chirica",
          "Dalla Costa",
          "Once De Abril",
          "Pozo Verde",
          "Simón Bolívar",
          "Unare",
          "Universidad",
          "Vista Al Sol",
          "Yocoima",
        ],
      },
      {
        municipio: "Cedeño",
        parroquias: [
          "Altagracia",
          "Ascensión Farreras",
          "Caicara Del Orinoco",
          "Guaniamo",
          "La Urbana",
          "Pijiguaos",
        ],
      },
      { municipio: "El Callao", parroquias: ["El Callao"] },
      {
        municipio: "Gran Sabana",
        parroquias: [
          "Esequibo Achiwib",
          "Esequibo Adelair",
          "Esequibo Aishalton",
          "Esequibo Altora Village",
          "Esequibo Ambrose Village",
          "Esequibo Annal (Anwai)",
          "Esequibo Apoteri",
          "Esequibo Arakwai Outstation",
          "Esequibo Atamadpau",
          "Esequibo Awariwaunau",
          "Esequibo Basha Village",
          "Esequibo Biloku",
          "Esequibo Bon Success",
          "Esequibo Burisanawa Village",
          "Esequibo Cajueiro",
          "Esequibo Dadanawa",
          "Esequibo Good Hope",
          "Esequibo Hart",
          "Esequibo Hawkins Mission",
          "Esequibo Hiawa",
          "Esequibo Illimir Village",
          "Esequibo Imprenza",
          "Esequibo Ishalton",
          "Esequibo Isherton",
          "Esequibo Jacaretinga",
          "Esequibo Johl",
          "Esequibo Kaibarupal Village",
          "Esequibo Karanambo",
          "Esequibo Karasabai",
          "Esequibo Kataliriwaui Village",
          "Esequibo Konashen",
          "Esequibo Kotoewau",
          "Esequibo Kumu Village",
          "Esequibo Kurukuru-Baibari",
          "Esequibo Kwaimatta",
          "Esequibo Kwatata",
          "Esequibo Lethem",
          "Esequibo Lumidpau",
          "Esequibo MacDonald",
          "Esequibo Macusi Village",
          "Esequibo Mamir Pawa",
          "Esequibo Manari",
          "Esequibo Marakanata",
          "Esequibo Mariwa Village",
          "Esequibo Maruranau",
          "Esequibo Massara",
          "Esequibo McTurk",
          "Esequibo Melvilles Ranch",
          "Esequibo Meritizero",
          "Esequibo Moco-Moco",
          "Esequibo Moreiro",
          "Esequibo Mountain Point",
          "Esequibo Mountain View",
          "Esequibo Muriwa Village",
          "Esequibo Nappi Village",
          "Esequibo Parabara",
          "Esequibo Paricaranal",
          "Esequibo Parishara",
          "Esequibo Patarinau",
          "Esequibo Peropo",
          "Esequibo Pilanawa",
          "Esequibo Pirara",
          "Esequibo Powisanau Village",
          "Esequibo Pukasanta Village",
          "Esequibo Sabernawau Village",
          "Esequibo Saint Ignatius",
          "Esequibo Sand Creek Village",
          "Esequibo Santa Fe",
          "Esequibo Sawariwau",
          "Esequibo Shea",
          "Esequibo Shulinab",
          "Esequibo Sunnyside",
          "Esequibo Surama",
          "Esequibo Tamton",
          "Esequibo Taruma",
          "Esequibo Tiger Pond Village",
          "Esequibo Tipuru",
          "Esequibo Toka",
          "Esequibo Wai-Wai",
          "Esequibo Waiwol Village",
          "Esequibo Wakadanawa",
          "Esequibo Wakakulud",
          "Esequibo Warimure",
          "Esequibo Wariwau",
          "Esequibo Waruma",
          "Esequibo Wichabal",
          "Esequibo Woweta",
          "Esequibo Yakarinta",
          "Esequibo Yepi Village",
          "Esequibo Yukupari",
          "Ikabaru",
          "Santa Elena De Uairén",
        ],
      },
      {
        municipio: "Heres",
        parroquias: [
          "Agua Salada",
          "Catedral",
          "José Antonio Páez",
          "La Sabanita",
          "Marhuanta",
          "Orinoco",
          "Panapana",
          "Vista Hermosa",
          "Zea",
        ],
      },
      { municipio: "Padre Pedro Chien", parroquias: ["El Palmar"] },
      {
        municipio: "Piar",
        parroquias: ["Andrés Eloy Blanco", "Pedro Cova", "Upata"],
      },
      { municipio: "Roscio", parroquias: ["Guasipati", "Salom"] },
      {
        municipio: "Sifontes",
        parroquias: [
          "Dalla Costa",
          "Esequibo Ajimipepai",
          "Esequibo Akar",
          "Esequibo Amamure",
          "Esequibo Amamuri",
          "Esequibo Amokokopai",
          "Esequibo Apanachi",
          "Esequibo Arau",
          "Esequibo Arawai",
          "Esequibo Arimu",
          "Esequibo Arnik Village",
          "Esequibo Assura",
          "Esequibo Aunama",
          "Esequibo Aurora",
          "Esequibo Awarabati",
          "Esequibo Barakara",
          "Esequibo Bartica",
          "Esequibo Butakari",
          "Esequibo Campbelltown",
          "Esequibo Chenapou (Chenapowu Village)",
          "Esequibo Ekereku",
          "Esequibo El Paso",
          "Esequibo Enachu Landing",
          "Esequibo Enachu Station",
          "Esequibo Enaruko Village",
          "Esequibo Golden Grove",
          "Esequibo Holmia",
          "Esequibo Imbaimadai",
          "Esequibo Ipichau (Ipishau, Ipisiau Village)",
          "Esequibo Issano",
          "Esequibo Isseneru",
          "Esequibo Itabac",
          "Esequibo Kaikan",
          "Esequibo Kalacoon",
          "Esequibo Kalakun",
          "Esequibo Kamana Village",
          "Esequibo Kamarang",
          "Esequibo Kamaria",
          "Esequibo Kamikusa",
          "Esequibo Kamuda",
          "Esequibo Kanapang Village",
          "Esequibo Kangaruma",
          "Esequibo Karisparu Village",
          "Esequibo Kartuni",
          "Esequibo Kato (Kato Village, Karto)",
          "Esequibo Kaywaek",
          "Esequibo Keweigek",
          "Esequibo Klip",
          "Esequibo Kokadai",
          "Esequibo Kopinang Mission",
          "Esequibo Kowaeng",
          "Esequibo Kukuieng (Kukui-Eng Village)",
          "Esequibo Kurachi",
          "Esequibo Kurikebaru (Kurikebary, Kurukabaru, Kurukabaru Village)",
          "Esequibo Kurutuku",
          "Esequibo Kwiokrebaru",
          "Esequibo Landing Oranopai",
          "Esequibo Lower Kamira",
          "Esequibo Mahdia",
          "Esequibo Maicobi",
          "Esequibo Maipuri Landing",
          "Esequibo Makari",
          "Esequibo Meruwang",
          "Esequibo Minata",
          "Esequibo Mongreppo",
          "Esequibo Monkey Mountain",
          "Esequibo Morowta",
          "Esequibo Muriakundi",
          "Esequibo Muruwawe",
          "Esequibo Opadal",
          "Esequibo Oranapai",
          "Esequibo Orinduik",
          "Esequibo Owenteik",
          "Esequibo Paramakatoi (Paramahatoi)",
          "Esequibo Pathawaru",
          "Esequibo Peters Mine",
          "Esequibo Pipillipai",
          "Esequibo Potaro Landing",
          "Esequibo Poterima",
          "Esequibo Princeville",
          "Esequibo Puruima",
          "Esequibo Puwa (Puwa Village)",
          "Esequibo Saint Edwards Mission",
          "Esequibo Saint Mary (Saint Marys)",
          "Esequibo Saint Marys",
          "Esequibo Saveretik",
          "Esequibo Sisipelin (Sisipelin Village)",
          "Esequibo Taruka",
          "Esequibo The Clip",
          "Esequibo Tumatumari",
          "Esequibo Tumatumari Landing",
          "Esequibo Tumereng",
          "Esequibo Upper Kamaria",
          "Esequibo Velgrad",
          "Esequibo Waioklepalul",
          "Esequibo Waioklepaluta Village",
          "Esequibo Waipa Village",
          "Esequibo Wandaik (Wandaik Village)",
          "Esequibo Wandapa (Wandapa Village, Waudapa Village)",
          "Esequibo Waramadong",
          "Esequibo Wiapri",
          "Esequibo Wineperu",
          "Esequibo Wolga",
          "San Isidro",
          "Tumeremo",
        ],
      },
      {
        municipio: "Sucre",
        parroquias: ["Aripao", "Guarataro", "Las Majadas", "Maripa", "Moitaco"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Miranda",
    municipios: [
      {
        municipio: "Acevedo",
        parroquias: [
          "Aragüita",
          "Arévalo González",
          "Capaya",
          "Caucagua",
          "El Café",
          "Marizapa",
          "Panaquire",
          "Ribas",
        ],
      },
      {
        municipio: "Andrés Bello",
        parroquias: ["Cumbo", "San José De Barlovento"],
      },
      {
        municipio: "Baruta",
        parroquias: [
          "Baruta",
          "El Cafetal",
          "Las Minas De Baruta",
          "Nuestra Señora Del Rosario",
        ],
      },
      {
        municipio: "Bolivariano Guaicaipuro",
        parroquias: [
          "Altagracia De La Montaña",
          "Cecilio Acosta",
          "El Jarillo",
          "Los Teques",
          "Paracotos",
          "San Pedro",
          "Tácata",
        ],
      },
      { municipio: "Brión", parroquias: ["Curiepe", "Higuerote", "Tacarigua"] },
      { municipio: "Buroz", parroquias: ["Mamporal"] },
      { municipio: "Carrizal", parroquias: ["Carrizal"] },
      { municipio: "Chacao", parroquias: ["Chacao"] },
      {
        municipio: "Cristobal Rojas",
        parroquias: ["Charallave", "Las Brisas"],
      },
      { municipio: "El Hatillo", parroquias: ["El Hatillo"] },
      {
        municipio: "Independencia",
        parroquias: ["El Cartanal", "Santa Teresa Del Tuy"],
      },
      {
        municipio: "Lander",
        parroquias: ["La Democracia", "Ocumare Del Tuy", "Santa Bárbara"],
      },
      { municipio: "Los Salias", parroquias: ["San Antonio Los Altos"] },
      {
        municipio: "Páez",
        parroquias: [
          "El Guapo",
          "Paparo",
          "Río Chico",
          "San Fernando Del Guapo",
          "Tacarigua De La Laguna",
        ],
      },
      { municipio: "Paz Castillo", parroquias: ["Santa Lucía"] },
      { municipio: "Pedro Gual", parroquias: ["Cúpira", "Machurucuto"] },
      { municipio: "Plaza", parroquias: ["Guarenas"] },
      {
        municipio: "Simón Bolívar",
        parroquias: ["San Antonio De Yare", "San Francisco De Yare"],
      },
      {
        municipio: "Sucre",
        parroquias: [
          "Caucagüita",
          "Filas De Mariches",
          "La Dolorita",
          "Leoncio Martinez",
          "Petare",
        ],
      },
      { municipio: "Urdaneta", parroquias: ["Cúa", "Nueva Cúa"] },
      { municipio: "Zamora", parroquias: ["Bolívar", "Guatire"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Carabobo",
    municipios: [
      {
        municipio: "Bejuma",
        parroquias: ["Bejuma", "Canoabo", "Simón Bolívar"],
      },
      {
        municipio: "Carlos Arvelo",
        parroquias: ["Belén", "Güigüe", "Tacarigua"],
      },
      { municipio: "Diego Ibarra", parroquias: ["Aguas Calientes", "Mariara"] },
      {
        municipio: "Guacara",
        parroquias: ["Ciudad Alianza", "Guacara", "Yagua"],
      },
      { municipio: "Juan José Mora", parroquias: ["Morón", "Urama"] },
      { municipio: "Libertador", parroquias: ["Independencia", "Tocuyito"] },
      { municipio: "Los Guayos", parroquias: ["Los Guayos"] },
      { municipio: "Miranda", parroquias: ["Miranda"] },
      { municipio: "Montalbán", parroquias: ["Montalbán"] },
      { municipio: "Naguanagua", parroquias: ["Naguanagua"] },
      {
        municipio: "Puerto Cabello",
        parroquias: [
          "Bartolomé Salom",
          "Borburata",
          "Democracia",
          "Fraternidad",
          "Goaigoaza",
          "Juan José Flores",
          "Patanemo",
          "Unión",
        ],
      },
      { municipio: "San Diego", parroquias: ["San Diego"] },
      { municipio: "San Joaquín", parroquias: ["San Joaquín"] },
      {
        municipio: "Valencia",
        parroquias: [
          "Candelaria",
          "Catedral",
          "El Socorro",
          "Miguel Peña",
          "Negro Primero",
          "Rafael Urdaneta",
          "San Blas",
          "San José",
          "Santa Rosa",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Cojedes",
    municipios: [
      {
        municipio: "Anzoátegui",
        parroquias: ["Cojedes", "Juan De Mata Suárez"],
      },
      { municipio: "El Pao", parroquias: ["El Pao"] },
      {
        municipio: "Ezequiel Zamora",
        parroquias: [
          "Juan Ángel Bravo",
          "Manuel Manrique",
          "San Carlos De Austria",
        ],
      },
      { municipio: "Girardot", parroquias: ["El Baúl", "Sucre"] },
      { municipio: "Lima Blanco", parroquias: ["La Aguadita", "Macapo"] },
      {
        municipio: "Ricaurte",
        parroquias: ["El Amparo", "Libertad De Cojedes"],
      },
      { municipio: "Romulo Gallegos", parroquias: ["Romulo Gallegos"] },
      {
        municipio: "Tinaco",
        parroquias: ["General En Jefe José Laurencio Silva"],
      },
      { municipio: "Tinaquillo", parroquias: ["Tinaquillo"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Delta Amacuro",
    municipios: [
      {
        municipio: "Antonio Diaz",
        parroquias: [
          "Almirante Luis Brión",
          "Curiapo",
          "Esequibo Aberdeen",
          "Esequibo Abrams Zuil",
          "Esequibo Acquero",
          "Esequibo Adventure",
          "Esequibo Affiance",
          "Esequibo Airy Hall",
          "Esequibo Akawini Mission",
          "Esequibo Amazon",
          "Esequibo Andrews",
          "Esequibo Anna Regina",
          "Esequibo Annandale",
          "Esequibo Arakaka",
          "Esequibo Aurora",
          "Esequibo Aurora Estate",
          "Esequibo Barabina Hill",
          "Esequibo Baramani",
          "Esequibo Baramita",
          "Esequibo Bel Alliance",
          "Esequibo Bethany",
          "Esequibo Better Hope",
          "Esequibo Better Success",
          "Esequibo Bountry Hall",
          "Esequibo Bush Lot",
          "Esequibo Capoey",
          "Esequibo Charity",
          "Esequibo Chinese Landing",
          "Esequibo Columbia",
          "Esequibo Cotton Field",
          "Esequibo Cullen",
          "Esequibo Cummingsburg",
          "Esequibo Danielstown",
          "Esequibo Dawa",
          "Esequibo Devonshire Castle",
          "Esequibo Dryshore",
          "Esequibo Durung Bang",
          "Esequibo Eurowa",
          "Esequibo Fair Field",
          "Esequibo Fear Not",
          "Esequibo Five Star",
          "Esequibo Golden Fleece",
          "Esequibo Good Hope",
          "Esequibo Hampton Court",
          "Esequibo Henritta",
          "Esequibo Hibernia",
          "Esequibo Hobediah",
          "Esequibo Hoff Van Aurich",
          "Esequibo Hosororo",
          "Esequibo Hotakwai",
          "Esequibo Huis T Dieren",
          "Esequibo Iguapa",
          "Esequibo Ipotaikuru",
          "Esequibo Issororo",
          "Esequibo Kabakaburi",
          "Esequibo Kaituma",
          "Esequibo Kakerit",
          "Esequibo Kamwatta Hill",
          "Esequibo Kariakau",
          "Esequibo Konora",
          "Esequibo Koriabo",
          "Esequibo Kumaka",
          "Esequibo Kwebanna",
          "Esequibo La Juanita",
          "Esequibo La Unión",
          "Esequibo Land Of Plenty",
          "Esequibo Lima",
          "Esequibo Little Alliance",
          "Esequibo Mabaruma",
          "Esequibo Machabo",
          "Esequibo Manaka",
          "Esequibo Manari",
          "Esequibo Manawarin",
          "Esequibo Maria's Lodge",
          "Esequibo Marlborough",
          "Esequibo Matthew's Ridge",
          "Esequibo Middlesex",
          "Esequibo Mission Landing",
          "Esequibo Morawhanna",
          "Esequibo Moruca",
          "Esequibo Mount Everard",
          "Esequibo Mubohina",
          "Esequibo New Road",
          "Esequibo Onderneemin",
          "Esequibo Pakera",
          "Esequibo Paradise",
          "Esequibo Parapimai",
          "Esequibo Perseverance",
          "Esequibo Perth",
          "Esequibo Pomona",
          "Esequibo Port Kaituma",
          "Esequibo Queenstown",
          "Esequibo Red Hill Settiement",
          "Esequibo Reliance",
          "Esequibo Richmond",
          "Esequibo Riverstown",
          "Esequibo Saint Bede's Mission",
          "Esequibo Saint Benedict Mission",
          "Esequibo Saint Nicholas",
          "Esequibo Santa Cruz",
          "Esequibo Santa Rosa",
          "Esequibo Saxacalli",
          "Esequibo Simiri",
          "Esequibo Sinclair Landing",
          "Esequibo Sirikie",
          "Esequibo Somerset And Berks",
          "Esequibo Sparta",
          "Esequibo Spring Garden",
          "Esequibo Suddie",
          "Esequibo Supenaan",
          "Esequibo Surprise Hill",
          "Esequibo Taymouth Manor",
          "Esequibo Three Friends",
          "Esequibo Towakaima",
          "Esequibo Waikerebi",
          "Esequibo Wakapau",
          "Esequibo Walton Hall",
          "Esequibo Waramuri",
          "Esequibo Waropoko Mission",
          "Esequibo Wauna Yarakita",
          "Esequibo Windsor Castle",
          "Esequibo Zorg",
          "Esequibo Zorg-En-Light",
          "Francisco Aniceto Lugo",
          "Manuel Renaud",
          "Padre Barral",
          "Santos De Abelgas",
        ],
      },
      {
        municipio: "Casacoima",
        parroquias: [
          "5 De Julio",
          "Imataca",
          "Juan Bautista Arismendi",
          "Manuel Piar",
          "Romulo Gallegos",
        ],
      },
      {
        municipio: "Pedernales",
        parroquias: ["Luis Beltrán Prieto Figueroa", "Pedernales"],
      },
      {
        municipio: "Tucupita",
        parroquias: [
          "José Vidal Marcano",
          "Juan Millán",
          "Leonardo Ruíz Pineda",
          "Mariscal Antonio José De Sucre",
          "Monseñor Argimiro García",
          "San José",
          "San Rafael",
          "Virgen Del Valle",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Dependencias Federales",
    municipios: [
      {
        municipio: "Archipiélago Los Roques",
        parroquias: [
          "Cayo Pirata",
          "Gran Roque",
          "Madrisqui (Madrisque - Cayo Rata)",
        ],
      },
      { municipio: "La Blanquilla", parroquias: ["La Blanquilla"] },
      { municipio: "La Orchila", parroquias: ["La Orchila"] },
      { municipio: "La Tortuga", parroquias: ["La Tortuga"] },
      { municipio: "Las Aves", parroquias: ["Las Aves"] },
      { municipio: "Los Frailes", parroquias: ["Los Frailes"] },
      { municipio: "Los Hermanos", parroquias: ["Los Hermanos"] },
      { municipio: "Los Testigos", parroquias: ["Los Testigos"] },
      {
        municipio: "Territorio Nacional",
        parroquias: ["Archipiélago De Los Roques", "Chimana", "Los Testigos"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Distrito Capital",
    municipios: ["Bolivariano Libertador"],
  },
  {
    pais: "Venezuela",
    estado: "Falcón",
    municipios: [
      "Acosta",
      "Bolívar",
      "Buchivacoa",
      "Cacique Manaure",
      "Carirubana",
      "Colina",
      "Dabajuro",
      "Democracia",
      "Falcón",
      "Federación",
      "Jacura",
      "Los Taques",
      "Mauroa",
      "Miranda",
      "Monseñor Iturriza",
      "Palmasola",
      "Petit",
      "Píritu",
      "San Francisco",
      "Silva",
      "Sucre",
      "Tocópero",
      "Unión",
      "Urumaco",
      "Zamora",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Guárico",
    municipios: [
      "Autónomo José Tadeo Monagas",
      "Camaguán",
      "Chaguaramas",
      "El Socorro",
      "Francisco De Miranda",
      "José Felix Ribas",
      "Juan Germán Roscio",
      "Juan José Rondón",
      "Julián Mellado",
      "Leonardo Infante",
      "Ortiz",
      "Pedro Zaraza",
      "San Gerónimo De Guayabal",
      "San José De Guaribe",
      "Santa María De Ipire",
    ],
  },
  { pais: "Venezuela", estado: "La Guaira", municipios: ["Vargas"] },
  {
    pais: "Venezuela",
    estado: "Lara",
    municipios: [
      "Andrés Eloy Blanco",
      "Crespo",
      "Iribarren",
      "Jiménez",
      "Morán",
      "Palavecino",
      "Simón Planas",
      "Torres",
      "Urdaneta",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Mérida",
    municipios: [
      "Alberto Adriani",
      "Andrés Bello",
      "Antonio Pinto Salinas",
      "Aricagua",
      "Arzobispo Chacón",
      "Campo Elías",
      "Caracciolo Parra Olmedo",
      "Cardenal Quintero",
      "Guaraque",
      "Julio César Salas",
      "Justo Briceño",
      "Libertador",
      "Miranda",
      "Obispo Ramos De Lora",
      "Padre Noguera",
      "Pueblo Llano",
      "Rangel",
      "Rivas Dávila",
      "Santos Marquina",
      "Sucre",
      "Tovar",
      "Tulio Febres Cordero",
      "Zea",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Monagas",
    municipios: [
      "Acosta",
      "Aguasay",
      "Bolívar",
      "Caripe",
      "Cedeño",
      "Ezequiel Zamora",
      "Libertador",
      "Maturín",
      "Piar",
      "Punceres",
      "Santa Bárbara",
      "Sotillo",
      "Uracoa",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Nueva Esparta",
    municipios: [
      "Antolín Del Campo",
      "Arismendi",
      "Díaz",
      "García",
      "Gómez",
      "Maneiro",
      "Marcano",
      "Mariño",
      "Península De Macanao",
      "Tubores",
      "Villalba",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Portuguesa",
    municipios: [
      "Agua Blanca",
      "Araure",
      "Esteller",
      "Guanare",
      "Guanarito",
      "Monseñor José Vicente De Unda",
      "Ospino",
      "Páez",
      "Papelón",
      "San Genaro De Boconoito",
      "San Rafael De Onoto",
      "Santa Rosalía",
      "Sucre",
      "Turén",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Sucre",
    municipios: [
      "Andrés Eloy Blanco",
      "Andrés Mata",
      "Arismendi",
      "Benítez",
      "Bermúdez",
      "Bolívar",
      "Cajigal",
      "Cruz Salmerón Acosta",
      "Libertador",
      "Mariño",
      "Mejía",
      "Montes",
      "Ribero",
      "Sucre",
      "Valdez",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Táchira",
    municipios: [
      "Andrés Bello",
      "Antonio Rómulo Costa",
      "Ayacucho",
      "Bolívar",
      "Cárdenas",
      "Cordoba",
      "Fernández Feo",
      "Francisco De Miranda",
      "García De Hevia",
      "Guásimos",
      "Independencia",
      "Jáuregui",
      "José María Vargas",
      "Junín",
      "Libertad",
      "Libertador",
      "Lobatera",
      "Michelena",
      "Panamericano",
      "Pedro María Ureña",
      "Rafael Urdaneta",
      "Samuel Darío Maldonado",
      "San Cristóbal",
      "San Judas Tadeo",
      "Seboruco",
      "Simón Rodríguez",
      "Sucre",
      "Torbes",
      "Uribante",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Trujillo",
    municipios: [
      "Andrés Bello",
      "Boconó",
      "Bolívar",
      "Candelaria",
      "Carache",
      "Escuque",
      "José Felipe Márquez Cañizales",
      "Juan Vicente Campo Elías",
      "La Ceiba",
      "Miranda",
      "Monte Carmelo",
      "Motatán",
      "Pampán",
      "Pampanito",
      "Rafael Rangel",
      "San Rafael De Carvajal",
      "Sucre",
      "Trujillo",
      "Urdaneta",
      "Valera",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Yaracuy",
    municipios: [
      "Aristides Bastidas",
      "Bolívar",
      "Bruzual",
      "Cocorote",
      "Independencia",
      "José Antonio Páez",
      "La Trinidad",
      "Manuel Monge",
      "Nirgua",
      "Peña",
      "San Felipe",
      "Sucre",
      "Urachiche",
      "Veroes",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Zulia",
    municipios: [
      "Almirante Padilla",
      "Baralt",
      "Cabimas",
      "Catatumbo",
      "Colon",
      "Francisco Javier Pulgar",
      "Indigena Bolivariano Guajira",
      "Jesús Enrique Lossada",
      "Jesús María Semprún",
      "La Cañada De Urdaneta",
      "Lagunillas",
      "Machiques De Perijá",
      "Mara",
      "Maracaibo",
      "Miranda",
      "Rosario De Perijá",
      "San Francisco",
      "Santa Rita",
      "Simón Bolívar",
      "Sucre",
      "Valmore Rodríguez",
    ],
  },
];

module.exports = {
  parroquias,
};
