const parroquias = [
  {
    pais: "Venezuela",
    estado: "Amazonas",
    municipios: [
      {
        municipio: "Autónomo Alto Orinoco",
        parroquias: [
          "Alto Orinoco",
          "Huachamacare",
          "La Esmeralda - Alto Orinoco",
          "Marawaka",
          "Mavaca",
          "Sierra Parima",
        ],
      },
      {
        municipio: "Autónomo Atabapo",
        parroquias: ["Caname", "San Fernando De Atabapo", "Ucata", "Yapacana"],
      },
      {
        municipio: "Autónomo Atures",
        parroquias: [
          "Fernando Girón Tovar",
          "Luis Alberto Gómez",
          "Parhueña",
          "Platanillal",
        ],
      },
      {
        municipio: "Autónomo Autana",
        parroquias: [
          "Guayapo",
          "Isla Ratón",
          "Munduapo",
          "Samariapo",
          "Sipapo",
        ],
      },
      {
        municipio: "Autónomo Manapiare",
        parroquias: [
          "Alto Ventuari",
          "Bajo Ventuari",
          "Medio Ventuari",
          "San Juan De Manapiare",
        ],
      },
      {
        municipio: "Autónomo Maroa",
        parroquias: ["Comunidad", "Maroa", "Victorino"],
      },
      {
        municipio: "Autónomo Río Negro",
        parroquias: [
          "Casiquiare",
          "Cocuy",
          "San Carlos De Río Negro",
          "Solano",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Anzoátegui",
    municipios: [
      {
        municipio: "Anaco",
        parroquias: ["Anaco", "Buena Vista", "San Joaquín"],
      },
      { municipio: "Aragua", parroquias: ["Aragua", "Cachipo"] },
      {
        municipio: "Diego Bautista Urbaneja",
        parroquias: ["El Morro", "Lecherías"],
      },
      {
        municipio: "Fernando De Peñalver",
        parroquias: [
          "Puerto Píritu - Fernando De Peñalver",
          "San Miguel",
          "Sucre",
        ],
      },
      {
        municipio: "Francisco De Miranda",
        parroquias: [
          "Atapirire",
          "Boca Del Pao",
          "El Pao",
          "Pariaguán - Francisco De Miranda",
        ],
      },
      {
        municipio: "Francisco Del Carmen Carvajal",
        parroquias: ["Santa Bárbara", "Valle De Guanape"],
      },
      { municipio: "Guanta", parroquias: ["Chorrerón", "Guanta"] },
      {
        municipio: "Independencia",
        parroquias: ["La Soledad - Independencia", "Mamo"],
      },
      {
        municipio: "José Gregorio Monagas",
        parroquias: [
          "Mapire - José Gregorio Monagas",
          "Piar",
          "San Diego De Cabrutica",
          "Santa Clara",
          "Uverito",
          "Zuata",
        ],
      },
      {
        municipio: "Juan Antonio Sotillo",
        parroquias: ["Pozuelos", "Puerto La Cruz"],
      },
      { municipio: "Juan Manuel Cajigal", parroquias: ["Onoto", "San Pablo"] },
      {
        municipio: "Libertad",
        parroquias: ["El Carito", "San Mateo - Libertad", "Santa Inés"],
      },
      {
        municipio: "Manuel Ezequiel Bruzual",
        parroquias: ["Clarines", "Guanape", "Sabana De Uchire"],
      },
      {
        municipio: "Pedro María Freites",
        parroquias: [
          "Cantaura - Pedro María Freites",
          "Libertador",
          "Santa Rosa",
          "Urica",
        ],
      },
      { municipio: "Píritu", parroquias: ["Píritu", "San Francisco"] },
      { municipio: "San José De Guanipa", parroquias: ["San José De Guanipa"] },
      {
        municipio: "San Juan De Capistrano",
        parroquias: ["Boca De Chávez", "Boca Uchire"],
      },
      { municipio: "Santa Ana", parroquias: ["Pueblo Nuevo", "Santa Ana"] },
      {
        municipio: "Simón Bolívar",
        parroquias: [
          "Bergantin",
          "Caigua",
          "El Carmen",
          "El Pilar",
          "Naricual",
          "San Cristobal",
        ],
      },
      {
        municipio: "Simón Rodríguez",
        parroquias: ["Edmundo Barrios", "Miguel Otero Silva"],
      },
      {
        municipio: "Sir Arthur Mc Gregor",
        parroquias: ["El Chaparro", "Tomás Alfaro Calatrava"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Apure",
    municipios: [
      {
        municipio: "Achaguas",
        parroquias: [
          "Achaguas",
          "Apurito",
          "El Yagual",
          "Guachara",
          "Mucuritas",
          "Queseras Del Medio",
        ],
      },
      { municipio: "Biruaca", parroquias: ["Biruaca"] },
      {
        municipio: "Muñoz",
        parroquias: [
          "Bruzual",
          "Mantecal",
          "Quintero",
          "Rincón Hondo",
          "San Vicente",
        ],
      },
      {
        municipio: "Páez",
        parroquias: [
          "Aramendi",
          "El Amparo",
          "Guasdualito",
          "San Camilo",
          "Urdaneta",
        ],
      },
      {
        municipio: "Pedro Camejo",
        parroquias: ["Codazzi", "Cunaviche", "San Juan De Payara"],
      },
      { municipio: "Rómulo Gallegos", parroquias: ["Elorza", "La Trinidad"] },
      {
        municipio: "San Fernando",
        parroquias: [
          "El Recreo",
          "Peñalver",
          "San Fernando",
          "San Rafael De Atamaica",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Aragua",
    municipios: [
      { municipio: "Bolívar", parroquias: ["San Mateo - Bolívar"] },
      { municipio: "Camatagua", parroquias: ["Camatagua", "Carmen De Cura"] },
      {
        municipio: "Francisco Linares Alcántara",
        parroquias: [
          "Francisco De Miranda",
          "Monseñor Feliciano González - Paraparal",
          "Santa Rita - Francisco Linares Alcántara",
        ],
      },
      {
        municipio: "Girardot",
        parroquias: [
          "Andrés Eloy Blanco",
          "Choroní",
          "Joaquín Crespo",
          "José Casanova Godoy",
          "Las Delicias",
          "Los Tacariguas",
          "Madre María De San José",
          "Pedro José Ovalles",
        ],
      },
      { municipio: "José Ángel Lamas", parroquias: ["Capital Santa Cruz"] },
      {
        municipio: "José Félix Rivas",
        parroquias: [
          "Castor Nieves Ríos",
          "La Victoria - Juan Vicente Bolívar",
          "Las Guacamayas",
          "Pao De Zárate",
          "Zuata",
        ],
      },
      { municipio: "José Rafael Revenga", parroquias: ["El Consejo"] },
      {
        municipio: "Libertador",
        parroquias: ["Palo Negro - Libertador", "San Martín De Porres"],
      },
      {
        municipio: "Mario Briceño Iragorry",
        parroquias: ["Caña De Azúcar", "El Limón - Mario Briceño Iragorry"],
      },
      {
        municipio: "Ocumare De La Costa De Oro",
        parroquias: ["Ocumare De La Costa"],
      },
      {
        municipio: "San Casimiro",
        parroquias: [
          "Güiripa",
          "Ollas De Caramacate",
          "San Casimiro",
          "Valle Morín",
        ],
      },
      { municipio: "San Sebastián", parroquias: ["San Sebastián"] },
      {
        municipio: "Santiago Mariño",
        parroquias: [
          "Alfredo Pacheco Miranda",
          "Arévalo Aponte",
          "Chuao",
          "Samán De Güere",
          "Turmero - Santiago Mariño",
        ],
      },
      {
        municipio: "Santos Michelena",
        parroquias: ["Las Tejerías - Santos Michelena", "Tiara"],
      },
      { municipio: "Sucre", parroquias: ["Bella Vista", "Cagua - Sucre"] },
      { municipio: "Tovar", parroquias: ["Colonia Tovar"] },
      {
        municipio: "Urdaneta",
        parroquias: [
          "Barbacoas - Urdaneta",
          "Las Peñitas",
          "San Francisco De Cara",
          "Taguay",
        ],
      },
      {
        municipio: "Zamora",
        parroquias: [
          "Augusto Mijares",
          "Magdaleno",
          "San Francisco De Asís",
          "Valles De Tucutunemo - Los Bagres",
          "Villa De Cura - Zamora",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Barinas",
    municipios: [
      {
        municipio: "Alberto Arvelo Torrealba",
        parroquias: ["Rodríguez Domínguez", "Sabaneta"],
      },
      {
        municipio: "Andrés Eloy Blanco",
        parroquias: ["El Cantón", "Puerto Vivas", "Santa Cruz De Guacas"],
      },
      {
        municipio: "Antonio José De Sucre",
        parroquias: ["Andrés Bello", "Nicolás Pulido", "Ticoporo"],
      },
      {
        municipio: "Arismendi",
        parroquias: ["Arismendi", "Guadarrama", "La Unión", "San Antonio"],
      },
      {
        municipio: "Barinas",
        parroquias: [
          "Alfredo Arvelo Larriva",
          "Alto Barinas",
          "Barinas",
          "Corazón De Jesús",
          "Dominga Ortiz De Páez",
          "El Carmen",
          "Juan Antonio Rodríguez Domínguez",
          "Manuel Palacio Fajardo",
          "Ramón Ignacio Méndez",
          "Rómulo Betancourt",
          "San Silvestre",
          "Santa Inés",
          "Santa Lucía",
          "Torunos",
        ],
      },
      {
        municipio: "Bolívar",
        parroquias: ["Altamira", "Barinitas", "Calderas"],
      },
      {
        municipio: "Cruz Paredes",
        parroquias: ["Barrancas", "El Socorro", "Masparrito"],
      },
      {
        municipio: "Ezequiel Zamora",
        parroquias: [
          "José Ignacio Del Pumar",
          "Pedro Briceño Méndez",
          "Ramón Ignacio Méndez",
          "Santa Bárbara",
        ],
      },
      {
        municipio: "Obispos",
        parroquias: ["El Real", "La Luz", "Los Guasimitos", "Obispos"],
      },
      {
        municipio: "Pedraza",
        parroquias: [
          "Ciudad Bolivia",
          "Ignacio Briceño",
          "José Félix Ribas",
          "Páez",
        ],
      },
      {
        municipio: "Rojas",
        parroquias: [
          "Dolores",
          "Libertad",
          "Palacio Fajardo",
          "Santa Rosa",
          "Simón Rodríguez",
        ],
      },
      {
        municipio: "Sosa",
        parroquias: [
          "Ciudad De Nutrias",
          "El Regalo",
          "Puerto De Nutrias",
          "Santa Catalina",
          "Simón Bolívar",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Bolívar",
    municipios: [
      {
        municipio: "Bolivariano Angostura",
        parroquias: [
          "Barceloneta",
          "Ciudad Piar",
          "San Francisco",
          "Santa Bárbara",
        ],
      },
      {
        municipio: "Caroní",
        parroquias: [
          "5 De Julio",
          "Cachamay",
          "Chirica",
          "Dalla Costa",
          "Once De Abril",
          "Pozo Verde",
          "Simón Bolívar",
          "Unare",
          "Universidad",
          "Vista Al Sol",
          "Yocoima",
        ],
      },
      {
        municipio: "Cedeño",
        parroquias: [
          "Altagracia",
          "Ascensión Farreras",
          "Caicara Del Orinoco",
          "Guaniamo",
          "La Urbana",
          "Pijiguaos",
        ],
      },
      { municipio: "El Callao", parroquias: ["El Callao"] },
      {
        municipio: "Gran Sabana",
        parroquias: [
          "Esequibo Achiwib",
          "Esequibo Adelair",
          "Esequibo Aishalton",
          "Esequibo Altora Village",
          "Esequibo Ambrose Village",
          "Esequibo Annal (Anwai)",
          "Esequibo Apoteri",
          "Esequibo Arakwai Outstation",
          "Esequibo Atamadpau",
          "Esequibo Awariwaunau",
          "Esequibo Basha Village",
          "Esequibo Biloku",
          "Esequibo Bon Success",
          "Esequibo Burisanawa Village",
          "Esequibo Cajueiro",
          "Esequibo Dadanawa",
          "Esequibo Good Hope",
          "Esequibo Hart",
          "Esequibo Hawkins Mission",
          "Esequibo Hiawa",
          "Esequibo Illimir Village",
          "Esequibo Imprenza",
          "Esequibo Ishalton",
          "Esequibo Isherton",
          "Esequibo Jacaretinga",
          "Esequibo Johl",
          "Esequibo Kaibarupal Village",
          "Esequibo Karanambo",
          "Esequibo Karasabai",
          "Esequibo Kataliriwaui Village",
          "Esequibo Konashen",
          "Esequibo Kotoewau",
          "Esequibo Kumu Village",
          "Esequibo Kurukuru-Baibari",
          "Esequibo Kwaimatta",
          "Esequibo Kwatata",
          "Esequibo Lethem",
          "Esequibo Lumidpau",
          "Esequibo MacDonald",
          "Esequibo Macusi Village",
          "Esequibo Mamir Pawa",
          "Esequibo Manari",
          "Esequibo Marakanata",
          "Esequibo Mariwa Village",
          "Esequibo Maruranau",
          "Esequibo Massara",
          "Esequibo McTurk",
          "Esequibo Melvilles Ranch",
          "Esequibo Meritizero",
          "Esequibo Moco-Moco",
          "Esequibo Moreiro",
          "Esequibo Mountain Point",
          "Esequibo Mountain View",
          "Esequibo Muriwa Village",
          "Esequibo Nappi Village",
          "Esequibo Parabara",
          "Esequibo Paricaranal",
          "Esequibo Parishara",
          "Esequibo Patarinau",
          "Esequibo Peropo",
          "Esequibo Pilanawa",
          "Esequibo Pirara",
          "Esequibo Powisanau Village",
          "Esequibo Pukasanta Village",
          "Esequibo Sabernawau Village",
          "Esequibo Saint Ignatius",
          "Esequibo Sand Creek Village",
          "Esequibo Santa Fe",
          "Esequibo Sawariwau",
          "Esequibo Shea",
          "Esequibo Shulinab",
          "Esequibo Sunnyside",
          "Esequibo Surama",
          "Esequibo Tamton",
          "Esequibo Taruma",
          "Esequibo Tiger Pond Village",
          "Esequibo Tipuru",
          "Esequibo Toka",
          "Esequibo Wai-Wai",
          "Esequibo Waiwol Village",
          "Esequibo Wakadanawa",
          "Esequibo Wakakulud",
          "Esequibo Warimure",
          "Esequibo Wariwau",
          "Esequibo Waruma",
          "Esequibo Wichabal",
          "Esequibo Woweta",
          "Esequibo Yakarinta",
          "Esequibo Yepi Village",
          "Esequibo Yukupari",
          "Ikabaru",
          "Santa Elena De Uairén",
        ],
      },
      {
        municipio: "Heres",
        parroquias: [
          "Agua Salada",
          "Catedral",
          "José Antonio Páez",
          "La Sabanita",
          "Marhuanta",
          "Orinoco",
          "Panapana",
          "Vista Hermosa",
          "Zea",
        ],
      },
      { municipio: "Padre Pedro Chien", parroquias: ["El Palmar"] },
      {
        municipio: "Piar",
        parroquias: ["Andrés Eloy Blanco", "Pedro Cova", "Upata"],
      },
      { municipio: "Roscio", parroquias: ["Guasipati", "Salom"] },
      {
        municipio: "Sifontes",
        parroquias: [
          "Dalla Costa",
          "Esequibo Ajimipepai",
          "Esequibo Akar",
          "Esequibo Amamure",
          "Esequibo Amamuri",
          "Esequibo Amokokopai",
          "Esequibo Apanachi",
          "Esequibo Arau",
          "Esequibo Arawai",
          "Esequibo Arimu",
          "Esequibo Arnik Village",
          "Esequibo Assura",
          "Esequibo Aunama",
          "Esequibo Aurora",
          "Esequibo Awarabati",
          "Esequibo Barakara",
          "Esequibo Bartica",
          "Esequibo Butakari",
          "Esequibo Campbelltown",
          "Esequibo Chenapou (Chenapowu Village)",
          "Esequibo Ekereku",
          "Esequibo El Paso",
          "Esequibo Enachu Landing",
          "Esequibo Enachu Station",
          "Esequibo Enaruko Village",
          "Esequibo Golden Grove",
          "Esequibo Holmia",
          "Esequibo Imbaimadai",
          "Esequibo Ipichau (Ipishau, Ipisiau Village)",
          "Esequibo Issano",
          "Esequibo Isseneru",
          "Esequibo Itabac",
          "Esequibo Kaikan",
          "Esequibo Kalacoon",
          "Esequibo Kalakun",
          "Esequibo Kamana Village",
          "Esequibo Kamarang",
          "Esequibo Kamaria",
          "Esequibo Kamikusa",
          "Esequibo Kamuda",
          "Esequibo Kanapang Village",
          "Esequibo Kangaruma",
          "Esequibo Karisparu Village",
          "Esequibo Kartuni",
          "Esequibo Kato (Kato Village, Karto)",
          "Esequibo Kaywaek",
          "Esequibo Keweigek",
          "Esequibo Klip",
          "Esequibo Kokadai",
          "Esequibo Kopinang Mission",
          "Esequibo Kowaeng",
          "Esequibo Kukuieng (Kukui-Eng Village)",
          "Esequibo Kurachi",
          "Esequibo Kurikebaru (Kurikebary, Kurukabaru, Kurukabaru Village)",
          "Esequibo Kurutuku",
          "Esequibo Kwiokrebaru",
          "Esequibo Landing Oranopai",
          "Esequibo Lower Kamira",
          "Esequibo Mahdia",
          "Esequibo Maicobi",
          "Esequibo Maipuri Landing",
          "Esequibo Makari",
          "Esequibo Meruwang",
          "Esequibo Minata",
          "Esequibo Mongreppo",
          "Esequibo Monkey Mountain",
          "Esequibo Morowta",
          "Esequibo Muriakundi",
          "Esequibo Muruwawe",
          "Esequibo Opadal",
          "Esequibo Oranapai",
          "Esequibo Orinduik",
          "Esequibo Owenteik",
          "Esequibo Paramakatoi (Paramahatoi)",
          "Esequibo Pathawaru",
          "Esequibo Peters Mine",
          "Esequibo Pipillipai",
          "Esequibo Potaro Landing",
          "Esequibo Poterima",
          "Esequibo Princeville",
          "Esequibo Puruima",
          "Esequibo Puwa (Puwa Village)",
          "Esequibo Saint Edwards Mission",
          "Esequibo Saint Mary (Saint Marys)",
          "Esequibo Saint Marys",
          "Esequibo Saveretik",
          "Esequibo Sisipelin (Sisipelin Village)",
          "Esequibo Taruka",
          "Esequibo The Clip",
          "Esequibo Tumatumari",
          "Esequibo Tumatumari Landing",
          "Esequibo Tumereng",
          "Esequibo Upper Kamaria",
          "Esequibo Velgrad",
          "Esequibo Waioklepalul",
          "Esequibo Waioklepaluta Village",
          "Esequibo Waipa Village",
          "Esequibo Wandaik (Wandaik Village)",
          "Esequibo Wandapa (Wandapa Village, Waudapa Village)",
          "Esequibo Waramadong",
          "Esequibo Wiapri",
          "Esequibo Wineperu",
          "Esequibo Wolga",
          "San Isidro",
          "Tumeremo",
        ],
      },
      {
        municipio: "Sucre",
        parroquias: ["Aripao", "Guarataro", "Las Majadas", "Maripa", "Moitaco"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Miranda",
    municipios: [
      {
        municipio: "Acevedo",
        parroquias: [
          "Aragüita",
          "Arévalo González",
          "Capaya",
          "Caucagua",
          "El Café",
          "Marizapa",
          "Panaquire",
          "Ribas",
        ],
      },
      {
        municipio: "Andrés Bello",
        parroquias: ["Cumbo", "San José De Barlovento"],
      },
      {
        municipio: "Baruta",
        parroquias: [
          "Baruta",
          "El Cafetal",
          "Las Minas De Baruta",
          "Nuestra Señora Del Rosario",
        ],
      },
      {
        municipio: "Bolivariano Guaicaipuro",
        parroquias: [
          "Altagracia De La Montaña",
          "Cecilio Acosta",
          "El Jarillo",
          "Los Teques",
          "Paracotos",
          "San Pedro",
          "Tácata",
        ],
      },
      { municipio: "Brión", parroquias: ["Curiepe", "Higuerote", "Tacarigua"] },
      { municipio: "Buroz", parroquias: ["Mamporal"] },
      { municipio: "Carrizal", parroquias: ["Carrizal"] },
      { municipio: "Chacao", parroquias: ["Chacao"] },
      {
        municipio: "Cristobal Rojas",
        parroquias: ["Charallave", "Las Brisas"],
      },
      { municipio: "El Hatillo", parroquias: ["El Hatillo"] },
      {
        municipio: "Independencia",
        parroquias: ["El Cartanal", "Santa Teresa Del Tuy"],
      },
      {
        municipio: "Lander",
        parroquias: ["La Democracia", "Ocumare Del Tuy", "Santa Bárbara"],
      },
      { municipio: "Los Salias", parroquias: ["San Antonio Los Altos"] },
      {
        municipio: "Páez",
        parroquias: [
          "El Guapo",
          "Paparo",
          "Río Chico",
          "San Fernando Del Guapo",
          "Tacarigua De La Laguna",
        ],
      },
      { municipio: "Paz Castillo", parroquias: ["Santa Lucía"] },
      { municipio: "Pedro Gual", parroquias: ["Cúpira", "Machurucuto"] },
      { municipio: "Plaza", parroquias: ["Guarenas"] },
      {
        municipio: "Simón Bolívar",
        parroquias: ["San Antonio De Yare", "San Francisco De Yare"],
      },
      {
        municipio: "Sucre",
        parroquias: [
          "Caucagüita",
          "Filas De Mariches",
          "La Dolorita",
          "Leoncio Martinez",
          "Petare",
        ],
      },
      { municipio: "Urdaneta", parroquias: ["Cúa", "Nueva Cúa"] },
      { municipio: "Zamora", parroquias: ["Bolívar", "Guatire"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Carabobo",
    municipios: [
      {
        municipio: "Bejuma",
        parroquias: ["Bejuma", "Canoabo", "Simón Bolívar"],
      },
      {
        municipio: "Carlos Arvelo",
        parroquias: ["Belén", "Güigüe", "Tacarigua"],
      },
      { municipio: "Diego Ibarra", parroquias: ["Aguas Calientes", "Mariara"] },
      {
        municipio: "Guacara",
        parroquias: ["Ciudad Alianza", "Guacara", "Yagua"],
      },
      { municipio: "Juan José Mora", parroquias: ["Morón", "Urama"] },
      { municipio: "Libertador", parroquias: ["Independencia", "Tocuyito"] },
      { municipio: "Los Guayos", parroquias: ["Los Guayos"] },
      { municipio: "Miranda", parroquias: ["Miranda"] },
      { municipio: "Montalbán", parroquias: ["Montalbán"] },
      { municipio: "Naguanagua", parroquias: ["Naguanagua"] },
      {
        municipio: "Puerto Cabello",
        parroquias: [
          "Bartolomé Salom",
          "Borburata",
          "Democracia",
          "Fraternidad",
          "Goaigoaza",
          "Juan José Flores",
          "Patanemo",
          "Unión",
        ],
      },
      { municipio: "San Diego", parroquias: ["San Diego"] },
      { municipio: "San Joaquín", parroquias: ["San Joaquín"] },
      {
        municipio: "Valencia",
        parroquias: [
          "Candelaria",
          "Catedral",
          "El Socorro",
          "Miguel Peña",
          "Negro Primero",
          "Rafael Urdaneta",
          "San Blas",
          "San José",
          "Santa Rosa",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Cojedes",
    municipios: [
      {
        municipio: "Anzoátegui",
        parroquias: ["Cojedes", "Juan De Mata Suárez"],
      },
      { municipio: "El Pao", parroquias: ["El Pao"] },
      {
        municipio: "Ezequiel Zamora",
        parroquias: [
          "Juan Ángel Bravo",
          "Manuel Manrique",
          "San Carlos De Austria",
        ],
      },
      { municipio: "Girardot", parroquias: ["El Baúl", "Sucre"] },
      { municipio: "Lima Blanco", parroquias: ["La Aguadita", "Macapo"] },
      {
        municipio: "Ricaurte",
        parroquias: ["El Amparo", "Libertad De Cojedes"],
      },
      { municipio: "Romulo Gallegos", parroquias: ["Romulo Gallegos"] },
      {
        municipio: "Tinaco",
        parroquias: ["General En Jefe José Laurencio Silva"],
      },
      { municipio: "Tinaquillo", parroquias: ["Tinaquillo"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Delta Amacuro",
    municipios: [
      {
        municipio: "Antonio Diaz",
        parroquias: [
          "Almirante Luis Brión",
          "Curiapo",
          "Esequibo Aberdeen",
          "Esequibo Abrams Zuil",
          "Esequibo Acquero",
          "Esequibo Adventure",
          "Esequibo Affiance",
          "Esequibo Airy Hall",
          "Esequibo Akawini Mission",
          "Esequibo Amazon",
          "Esequibo Andrews",
          "Esequibo Anna Regina",
          "Esequibo Annandale",
          "Esequibo Arakaka",
          "Esequibo Aurora",
          "Esequibo Aurora Estate",
          "Esequibo Barabina Hill",
          "Esequibo Baramani",
          "Esequibo Baramita",
          "Esequibo Bel Alliance",
          "Esequibo Bethany",
          "Esequibo Better Hope",
          "Esequibo Better Success",
          "Esequibo Bountry Hall",
          "Esequibo Bush Lot",
          "Esequibo Capoey",
          "Esequibo Charity",
          "Esequibo Chinese Landing",
          "Esequibo Columbia",
          "Esequibo Cotton Field",
          "Esequibo Cullen",
          "Esequibo Cummingsburg",
          "Esequibo Danielstown",
          "Esequibo Dawa",
          "Esequibo Devonshire Castle",
          "Esequibo Dryshore",
          "Esequibo Durung Bang",
          "Esequibo Eurowa",
          "Esequibo Fair Field",
          "Esequibo Fear Not",
          "Esequibo Five Star",
          "Esequibo Golden Fleece",
          "Esequibo Good Hope",
          "Esequibo Hampton Court",
          "Esequibo Henritta",
          "Esequibo Hibernia",
          "Esequibo Hobediah",
          "Esequibo Hoff Van Aurich",
          "Esequibo Hosororo",
          "Esequibo Hotakwai",
          "Esequibo Huis T Dieren",
          "Esequibo Iguapa",
          "Esequibo Ipotaikuru",
          "Esequibo Issororo",
          "Esequibo Kabakaburi",
          "Esequibo Kaituma",
          "Esequibo Kakerit",
          "Esequibo Kamwatta Hill",
          "Esequibo Kariakau",
          "Esequibo Konora",
          "Esequibo Koriabo",
          "Esequibo Kumaka",
          "Esequibo Kwebanna",
          "Esequibo La Juanita",
          "Esequibo La Unión",
          "Esequibo Land Of Plenty",
          "Esequibo Lima",
          "Esequibo Little Alliance",
          "Esequibo Mabaruma",
          "Esequibo Machabo",
          "Esequibo Manaka",
          "Esequibo Manari",
          "Esequibo Manawarin",
          "Esequibo Maria's Lodge",
          "Esequibo Marlborough",
          "Esequibo Matthew's Ridge",
          "Esequibo Middlesex",
          "Esequibo Mission Landing",
          "Esequibo Morawhanna",
          "Esequibo Moruca",
          "Esequibo Mount Everard",
          "Esequibo Mubohina",
          "Esequibo New Road",
          "Esequibo Onderneemin",
          "Esequibo Pakera",
          "Esequibo Paradise",
          "Esequibo Parapimai",
          "Esequibo Perseverance",
          "Esequibo Perth",
          "Esequibo Pomona",
          "Esequibo Port Kaituma",
          "Esequibo Queenstown",
          "Esequibo Red Hill Settiement",
          "Esequibo Reliance",
          "Esequibo Richmond",
          "Esequibo Riverstown",
          "Esequibo Saint Bede's Mission",
          "Esequibo Saint Benedict Mission",
          "Esequibo Saint Nicholas",
          "Esequibo Santa Cruz",
          "Esequibo Santa Rosa",
          "Esequibo Saxacalli",
          "Esequibo Simiri",
          "Esequibo Sinclair Landing",
          "Esequibo Sirikie",
          "Esequibo Somerset And Berks",
          "Esequibo Sparta",
          "Esequibo Spring Garden",
          "Esequibo Suddie",
          "Esequibo Supenaan",
          "Esequibo Surprise Hill",
          "Esequibo Taymouth Manor",
          "Esequibo Three Friends",
          "Esequibo Towakaima",
          "Esequibo Waikerebi",
          "Esequibo Wakapau",
          "Esequibo Walton Hall",
          "Esequibo Waramuri",
          "Esequibo Waropoko Mission",
          "Esequibo Wauna Yarakita",
          "Esequibo Windsor Castle",
          "Esequibo Zorg",
          "Esequibo Zorg-En-Light",
          "Francisco Aniceto Lugo",
          "Manuel Renaud",
          "Padre Barral",
          "Santos De Abelgas",
        ],
      },
      {
        municipio: "Casacoima",
        parroquias: [
          "5 De Julio",
          "Imataca",
          "Juan Bautista Arismendi",
          "Manuel Piar",
          "Romulo Gallegos",
        ],
      },
      {
        municipio: "Pedernales",
        parroquias: ["Luis Beltrán Prieto Figueroa", "Pedernales"],
      },
      {
        municipio: "Tucupita",
        parroquias: [
          "José Vidal Marcano",
          "Juan Millán",
          "Leonardo Ruíz Pineda",
          "Mariscal Antonio José De Sucre",
          "Monseñor Argimiro García",
          "San José",
          "San Rafael",
          "Virgen Del Valle",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Dependencias Federales",
    municipios: [
      {
        municipio: "Archipiélago Los Roques",
        parroquias: [
          "Cayo Pirata",
          "Gran Roque",
          "Madrisqui (Madrisque - Cayo Rata)",
        ],
      },
      { municipio: "La Blanquilla", parroquias: ["La Blanquilla"] },
      { municipio: "La Orchila", parroquias: ["La Orchila"] },
      { municipio: "La Tortuga", parroquias: ["La Tortuga"] },
      { municipio: "Las Aves", parroquias: ["Las Aves"] },
      { municipio: "Los Frailes", parroquias: ["Los Frailes"] },
      { municipio: "Los Hermanos", parroquias: ["Los Hermanos"] },
      { municipio: "Los Testigos", parroquias: ["Los Testigos"] },
      {
        municipio: "Territorio Nacional",
        parroquias: ["Archipiélago De Los Roques", "Chimana", "Los Testigos"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Distrito Capital",
    municipios: [
      {
        municipio: "Bolivariano Libertador",
        parroquias: [
          "23 De Enero",
          "Altagracia",
          "Antimano",
          "Candelaria",
          "Caricuao",
          "Catedral",
          "Coche",
          "El Junquito",
          "El Paraíso",
          "El Recreo",
          "El Valle",
          "La Pastora",
          "La Vega",
          "Macarao",
          "San Agustín",
          "San Bernardino",
          "San José",
          "San Juan",
          "San Pedro",
          "Santa Rosalía",
          "Santa Teresa",
          "Sucre",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Falcón",
    municipios: [
      {
        municipio: "Acosta",
        parroquias: [
          "Capadare",
          "La Pastora",
          "Libertador",
          "San Juan De Los Cayos",
        ],
      },
      { municipio: "Bolívar", parroquias: ["Aracua", "La Peña", "San Luis"] },
      {
        municipio: "Buchivacoa",
        parroquias: [
          "Bariro",
          "Borojó",
          "Capatárida",
          "Guajiro",
          "Seque",
          "Zazarida",
        ],
      },
      {
        municipio: "Cacique Manaure",
        parroquias: ["Yaracal - Cacique Manaure"],
      },
      {
        municipio: "Carirubana",
        parroquias: ["Carirubana", "Norte", "Punta Cardón", "Santa Ana"],
      },
      {
        municipio: "Colina",
        parroquias: [
          "Acurigua",
          "Guaibacoa",
          "La Vela De Coro",
          "Las Calderas",
          "Macoruca",
        ],
      },
      { municipio: "Dabajuro", parroquias: ["Dabajuro"] },
      {
        municipio: "Democracia",
        parroquias: [
          "Agua Clara",
          "Avaria",
          "Pedregal",
          "Piedra Grande",
          "Purereche",
        ],
      },
      {
        municipio: "Falcón",
        parroquias: [
          "Adaure",
          "Adícora",
          "Baraived",
          "Buena Vista",
          "El Hato",
          "El Vínculo",
          "Jadacaquiva",
          "Moruy",
          "Pueblo Nuevo",
        ],
      },
      {
        municipio: "Federación",
        parroquias: [
          "Agua Larga",
          "Churuguara",
          "El Paují",
          "Independencia",
          "Mapararí",
        ],
      },
      { municipio: "Jacura", parroquias: ["Agua Linda", "Araurima", "Jacura"] },
      { municipio: "Los Taques", parroquias: ["Judibana", "Los Taques"] },
      {
        municipio: "Mauroa",
        parroquias: ["Casigua", "Mene De Mauroa", "San Félix"],
      },
      {
        municipio: "Miranda",
        parroquias: [
          "Guzmán Guillermo",
          "Mitare",
          "Río Seco",
          "Sabaneta",
          "San Antonio",
          "San Gabriel",
          "Santa Ana",
        ],
      },
      {
        municipio: "Monseñor Iturriza",
        parroquias: ["Boca De Tocuyo", "Chichiriviche", "Tocuyo De La Costa"],
      },
      { municipio: "Palmasola", parroquias: ["Palmasola"] },
      { municipio: "Petit", parroquias: ["Cabure", "Colina", "Curimagua"] },
      { municipio: "Píritu", parroquias: ["Píritu", "San José De La Costa"] },
      { municipio: "San Francisco", parroquias: ["Mirimire - San Francisco"] },
      { municipio: "Silva", parroquias: ["Boca De Aroa", "Tucacas"] },
      { municipio: "Sucre", parroquias: ["Pecaya", "Sucre"] },
      { municipio: "Tocópero", parroquias: ["Tocópero"] },
      {
        municipio: "Unión",
        parroquias: ["El Charal", "Las Vegas Del Tuy", "Santa Cruz De Bucaral"],
      },
      { municipio: "Urumaco", parroquias: ["Bruzual", "Urumaco"] },
      {
        municipio: "Zamora",
        parroquias: [
          "La Cienaga",
          "La Soledad",
          "Pueblo Cumarebo",
          "Puerto Cumarebo",
          "Zazárida",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Guárico",
    municipios: [
      {
        municipio: "Autónomo José Tadeo Monagas",
        parroquias: [
          "Altagracia De Orituco",
          "Lezama",
          "Libertad De Orituco",
          "Paso Real De Macaira",
          "San Francisco De Macaira",
          "San Rafael De Orituco",
          "Soublette",
        ],
      },
      {
        municipio: "Camaguán",
        parroquias: ["Camaguán", "Puerto Miranda", "Uverito"],
      },
      { municipio: "Chaguaramas", parroquias: ["Chaguaramas"] },
      { municipio: "El Socorro", parroquias: ["El Socorro"] },
      {
        municipio: "Francisco De Miranda",
        parroquias: ["Calabozo", "El Calvario", "El Rastro", "Guardatinajas"],
      },
      {
        municipio: "José Felix Ribas",
        parroquias: ["San Rafael De Laya", "Tucupido"],
      },
      {
        municipio: "Juan Germán Roscio",
        parroquias: ["Cantagallo", "Parapara", "San Juan De Los Morros"],
      },
      {
        municipio: "Juan José Rondón",
        parroquias: ["Cabruta", "Las Mercedes", "Santa Rita De Manapire"],
      },
      { municipio: "Julián Mellado", parroquias: ["El Sombrero", "Sosa"] },
      {
        municipio: "Leonardo Infante",
        parroquias: ["Espino", "Valle De La Pascua"],
      },
      {
        municipio: "Ortiz",
        parroquias: [
          "Ortiz",
          "San Francisco De Tiznados",
          "San José De Tiznados",
          "San Lorenzo De Tiznados",
        ],
      },
      {
        municipio: "Pedro Zaraza",
        parroquias: ["San José De Unare", "Zaraza"],
      },
      {
        municipio: "San Gerónimo De Guayabal",
        parroquias: ["Cazorla", "Guayabal"],
      },
      { municipio: "San José De Guaribe", parroquias: ["San José De Guaribe"] },
      {
        municipio: "Santa María De Ipire",
        parroquias: ["Altamira", "Santa María De Ipire"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "La Guaira",
    municipios: [
      {
        municipio: "Vargas",
        parroquias: [
          "Caraballeda",
          "Carayaca",
          "Carlos Soublette",
          "Caruao",
          "Catia La Mar",
          "El Junko",
          "La Guaira",
          "Macuto",
          "Maiquetía",
          "Naiguatá",
          "Urimare",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Lara",
    municipios: [
      {
        municipio: "Andrés Eloy Blanco",
        parroquias: ["Pío Tamayo", "Quebrada Honda De Guache", "Yacambú"],
      },
      { municipio: "Crespo", parroquias: ["Fréitez", "José María Blanco"] },
      {
        municipio: "Iribarren",
        parroquias: [
          "Aguedo Felipe Alvarado",
          "Buena Vista",
          "Catedral",
          "Concepción",
          "El Cují",
          "Juan De Villegas",
          "Juárez",
          "Santa Rosa",
          "Tamaca",
          "Unión",
        ],
      },
      {
        municipio: "Jiménez",
        parroquias: [
          "Coronel Mariano Peraza",
          "Cuara",
          "Diego De Lozada",
          "José Bernardo Dorante",
          "Juan Bautista Rodríguez",
          "Paraíso De San José",
          "San Miguel",
          "Tintorero",
        ],
      },
      {
        municipio: "Morán",
        parroquias: [
          "Anzoátegui",
          "Bolívar",
          "Guárico",
          "Hilario Luna y Luna",
          "Humocaro Alto",
          "Humocaro Bajo",
          "La Candelaria",
          "Morán",
        ],
      },
      {
        municipio: "Palavecino",
        parroquias: ["Agua Viva", "Cabudare", "José Gregorio Bastidas"],
      },
      {
        municipio: "Simón Planas",
        parroquias: ["Buría", "Gustavo Vegas León", "Sarare"],
      },
      {
        municipio: "Torres",
        parroquias: [
          "Altagracia",
          "Antonio Díaz",
          "Camacaro",
          "Castañeda",
          "Cecilio Zubillaga",
          "Chiquinquirá",
          "El Blanco",
          "Espinoza Los Monteros",
          "Heriberto Arroyo",
          "Lara",
          "Las Mercedes",
          "Manuel Morillo",
          "Montaña Verde",
          "Montes De Oca",
          "Reyes Vargas",
          "Torres",
          "Trinidad Samuel",
        ],
      },
      {
        municipio: "Urdaneta",
        parroquias: ["Moroturo", "San Miguel", "Siquisique", "Xaguas"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Mérida",
    municipios: [
      {
        municipio: "Alberto Adriani",
        parroquias: [
          "Gabriel Picón González",
          "Héctor Amable Mora",
          "José Nucete Sardi",
          "Presidente Betancourt",
          "Presidente Páez",
          "Presidente Rómulo Gallegos",
          "Pulido Méndez",
        ],
      },
      { municipio: "Andrés Bello", parroquias: ["La Azulita - Andrés Bello"] },
      {
        municipio: "Antonio Pinto Salinas",
        parroquias: [
          "Mesa Bolívar",
          "Mesa De Las Palmas",
          "Santa Cruz De Mora",
        ],
      },
      { municipio: "Aricagua", parroquias: ["Aricagua", "San Antonio"] },
      {
        municipio: "Arzobispo Chacón",
        parroquias: [
          "Canaguá",
          "Capurí",
          "Chacantá",
          "El Molino",
          "Guaimaral",
          "Mucuchachí",
          "Mucutuy",
        ],
      },
      {
        municipio: "Campo Elías",
        parroquias: [
          "Acequias",
          "Fernández Peña",
          "Jají",
          "La Mesa",
          "Matriz",
          "Montalbán",
          "San José",
        ],
      },
      {
        municipio: "Caracciolo Parra Olmedo",
        parroquias: ["Florencio Ramírez", "Tucaní"],
      },
      {
        municipio: "Cardenal Quintero",
        parroquias: ["Las Piedras", "Santo Domingo"],
      },
      {
        municipio: "Guaraque",
        parroquias: ["Guaraque", "Mesa De Quintero", "Río Negro"],
      },
      { municipio: "Julio César Salas", parroquias: ["Arapuey", "Palmira"] },
      {
        municipio: "Justo Briceño",
        parroquias: ["San Cristóbal De Torondoy", "Torondoy"],
      },
      {
        municipio: "Libertador",
        parroquias: [
          "Antonio Spinetti Dini",
          "Arias",
          "Caracciolo Parra Pérez",
          "Domingo Peña",
          "El Llano",
          "El Morro",
          "Gonzalo Picón Febres",
          "Jacinto Plaza",
          "Juan Rodríguez Suárez",
          "Lasso De La Vega",
          "Los Nevados",
          "Mariano Picón Salas",
          "Milla",
          "Osuna Rodríguez",
          "Sagrario",
        ],
      },
      {
        municipio: "Miranda",
        parroquias: ["Andrés Eloy Blanco", "La Venta", "Piñango", "Timotes"],
      },
      {
        municipio: "Obispo Ramos De Lora",
        parroquias: [
          "Eloy Paredes",
          "San Rafael De Alcázar",
          "Santa Elena De Arenales",
        ],
      },
      { municipio: "Padre Noguera", parroquias: ["Santa María De Caparo"] },
      { municipio: "Pueblo Llano", parroquias: ["Pueblo Llano"] },
      {
        municipio: "Rangel",
        parroquias: [
          "Cacute",
          "La Toma",
          "Mucuchíes",
          "Mucurubá",
          "San Rafael",
        ],
      },
      {
        municipio: "Rivas Dávila",
        parroquias: ["Bailadores", "Gerónimo Maldonado"],
      },
      { municipio: "Santos Marquina", parroquias: ["Tabay"] },
      {
        municipio: "Sucre",
        parroquias: [
          "Chiguará",
          "Estánquez",
          "La Trampa",
          "Lagunillas",
          "Pueblo Nuevo Del Sur",
          "San Juan",
        ],
      },
      {
        municipio: "Tovar",
        parroquias: ["El Amparo", "El Llano", "San Francisco", "Tovar"],
      },
      {
        municipio: "Tulio Febres Cordero",
        parroquias: [
          "Independencia",
          "María De La Concepción Palacios Blanco",
          "Nueva Bolivia",
          "Santa Apolonia",
        ],
      },
      { municipio: "Zea", parroquias: ["Caño El Tigre", "Zea"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Monagas",
    municipios: [
      { municipio: "Acosta", parroquias: ["San Antonio", "San Francisco"] },
      { municipio: "Aguasay", parroquias: ["Aguasay"] },
      { municipio: "Bolívar", parroquias: ["Caripito"] },
      {
        municipio: "Caripe",
        parroquias: [
          "Caripe",
          "El Guácharo",
          "La Guanota",
          "Sabana De Piedra",
          "San Agustín",
          "Teresén",
        ],
      },
      {
        municipio: "Cedeño",
        parroquias: ["Areo", "Caicara", "San Félix", "Viento Fresco"],
      },
      {
        municipio: "Ezequiel Zamora",
        parroquias: ["El Tejero", "Punta De Mata"],
      },
      {
        municipio: "Libertador",
        parroquias: ["Chaguaramas", "Las Alhuacas", "Tabasca", "Temblador"],
      },
      {
        municipio: "Maturín",
        parroquias: [
          "Alto De Los Godos",
          "Boquerón",
          "El Corozo",
          "El Furrial",
          "Jusepín",
          "La Pica",
          "Las Cocuizas",
          "San Simón",
          "San Vicente",
          "Santa Cruz",
        ],
      },
      {
        municipio: "Piar",
        parroquias: [
          "Aparicio",
          "Aragua",
          "Chaguaramal",
          "El Pinto",
          "Guanaguana",
          "La Toscana",
          "Taguaya",
        ],
      },
      { municipio: "Punceres", parroquias: ["Cachipo", "Quiriquire"] },
      { municipio: "Santa Bárbara", parroquias: ["Santa Bárbara"] },
      {
        municipio: "Sotillo",
        parroquias: ["Barrancas", "Los Barrancos De Fajardo"],
      },
      { municipio: "Uracoa", parroquias: ["Uracoa"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Nueva Esparta",
    municipios: [
      {
        municipio: "Antolín Del Campo",
        parroquias: ["La Plaza De Paraguachí"],
      },
      { municipio: "Arismendi", parroquias: ["La Asunción"] },
      { municipio: "Díaz", parroquias: ["San Juan Bautista", "Zabala"] },
      {
        municipio: "García",
        parroquias: ["El Valle Del Espíritu Santo", "Francisco Fajardo"],
      },
      {
        municipio: "Gómez",
        parroquias: ["Bolívar", "Guevara", "Matasiete", "Santa Ana", "Sucre"],
      },
      { municipio: "Maneiro", parroquias: ["Aguirre", "Pampatar"] },
      { municipio: "Marcano", parroquias: ["Adrián", "Juan Griego"] },
      { municipio: "Mariño", parroquias: ["Porlamar"] },
      {
        municipio: "Península De Macanao",
        parroquias: ["Boca Del Río", "San Francisco"],
      },
      { municipio: "Tubores", parroquias: ["Los Barales", "Punta De Piedras"] },
      {
        municipio: "Villalba",
        parroquias: ["San Pedro De Coche", "Vicente Fuentes"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Portuguesa",
    municipios: [
      { municipio: "Agua Blanca", parroquias: ["Agua Blanca"] },
      { municipio: "Araure", parroquias: ["Araure", "Río Acarigua"] },
      { municipio: "Esteller", parroquias: ["Píritu", "Uveral"] },
      {
        municipio: "Guanare",
        parroquias: [
          "Córdoba",
          "Guanare",
          "San José De La Montaña",
          "San Juan De Guanaguanare",
          "Virgen De La Coromoto",
        ],
      },
      {
        municipio: "Guanarito",
        parroquias: ["Divina Pastora", "Guanarito", "Trinidad De La Capilla"],
      },
      {
        municipio: "Monseñor José Vicente De Unda",
        parroquias: ["Chabasquén", "Peña Blanca"],
      },
      {
        municipio: "Ospino",
        parroquias: ["Aparición", "La Estación", "Ospino"],
      },
      {
        municipio: "Páez",
        parroquias: ["Acarigua", "Payara", "Pimpinela", "Ramón Peraza"],
      },
      { municipio: "Papelón", parroquias: ["Caño Delgadito", "Papelón"] },
      {
        municipio: "San Genaro De Boconoito",
        parroquias: ["Antolín Tovar", "Boconoito"],
      },
      {
        municipio: "San Rafael De Onoto",
        parroquias: ["San Rafael De Onoto", "Santa Fe", "Thermo Morles"],
      },
      { municipio: "Santa Rosalía", parroquias: ["El Playón", "Florida"] },
      {
        municipio: "Sucre",
        parroquias: [
          "Biscucuy",
          "Concepción",
          "San José De Saguaz",
          "San Rafael Palo Alzado",
          "Uvencio Antonio Velásquez",
          "Villa Rosa",
        ],
      },
      {
        municipio: "Turén",
        parroquias: [
          "Canelones",
          "San Isidro Labrador",
          "Santa Cruz",
          "Villa Bruzual",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Sucre",
    municipios: [
      {
        municipio: "Andrés Eloy Blanco",
        parroquias: ["Mariño", "Rómulo Gallegos"],
      },
      {
        municipio: "Andrés Mata",
        parroquias: ["San José De Areocuar", "Tavera Acosta"],
      },
      {
        municipio: "Arismendi",
        parroquias: [
          "Antonio José De Sucre",
          "El Morro De Puerto Santo",
          "Puerto Santo",
          "Río Caribe",
          "San Juan Galdonas",
        ],
      },
      {
        municipio: "Benítez",
        parroquias: [
          "El Pilar",
          "El Rincón",
          "General Francisco Antonio Vásquez",
          "Guaraunos",
          "Tunapuicito",
          "Unión",
        ],
      },
      {
        municipio: "Bermúdez",
        parroquias: [
          "Bolívar",
          "Macarapana",
          "Santa Catalina",
          "Santa Rosa",
          "Santa Teresa",
        ],
      },
      { municipio: "Bolívar", parroquias: ["Marigüitar"] },
      {
        municipio: "Cajigal",
        parroquias: ["Libertad", "Paujil", "Yaguaraparo"],
      },
      {
        municipio: "Cruz Salmerón Acosta",
        parroquias: ["Araya", "Chacopata", "Manicuare"],
      },
      { municipio: "Libertador", parroquias: ["Campo Elias", "Tunapuy"] },
      {
        municipio: "Mariño",
        parroquias: [
          "Campo Claro",
          "Irapa",
          "Marabal",
          "San Antonio De Irapa",
          "Soro",
        ],
      },
      { municipio: "Mejía", parroquias: ["San Antonio Del Golfo"] },
      {
        municipio: "Montes",
        parroquias: [
          "Arenas",
          "Aricagua",
          "Cocollar",
          "Cumanacoa",
          "San Fernando",
          "San Lorenzo",
        ],
      },
      {
        municipio: "Ribero",
        parroquias: [
          "Cariaco",
          "Catuaro",
          "Rendón",
          "Santa Cruz",
          "Santa María",
        ],
      },
      {
        municipio: "Sucre",
        parroquias: [
          "Altagracia",
          "Ayacucho",
          "Gran Mariscal",
          "Raúl Leoni",
          "San Juan",
          "Santa Ines",
          "Valentin Valiente",
        ],
      },
      {
        municipio: "Valdez",
        parroquias: ["Bideau", "Cristóbal Colón", "Güiria", "Punta De Piedra"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Táchira",
    municipios: [
      { municipio: "Andrés Bello", parroquias: ["Cordero"] },
      { municipio: "Antonio Rómulo Costa", parroquias: ["Las Mesas"] },
      {
        municipio: "Ayacucho",
        parroquias: ["Ayacucho", "Rivas Berti", "San Pedro Del Río"],
      },
      {
        municipio: "Bolívar",
        parroquias: [
          "Isaías Medina Angarita",
          "Juan Vicente Gómez",
          "Palotal",
          "San Antonio Del Táchira",
        ],
      },
      {
        municipio: "Cárdenas",
        parroquias: ["Amenodoro Rangel Lamús", "La Florida", "Táriba"],
      },
      { municipio: "Cordoba", parroquias: ["Santa Ana"] },
      {
        municipio: "Fernández Feo",
        parroquias: [
          "Alberto Adriani",
          "San Rafael Del Piñal",
          "Santo Domingo",
        ],
      },
      {
        municipio: "Francisco De Miranda",
        parroquias: ["San José De Bolívar"],
      },
      {
        municipio: "García De Hevia",
        parroquias: ["Boca De Grita", "José Antonio Páez", "La Fría"],
      },
      { municipio: "Guásimos", parroquias: ["Palmira"] },
      {
        municipio: "Independencia",
        parroquias: ["Capacho Nuevo", "Juan Germán Roscio", "Román Cárdenas"],
      },
      {
        municipio: "Jáuregui",
        parroquias: [
          "Emilio Constantino Guerrero",
          "La Grita",
          "Monseñor Miguel Antonio Salas",
        ],
      },
      {
        municipio: "José María Vargas",
        parroquias: ["El Cobre", "José María Vargas"],
      },
      {
        municipio: "Junín",
        parroquias: ["Bramón", "Junín", "La Petrólea", "Quinimarí", "Rubio"],
      },
      {
        municipio: "Libertad",
        parroquias: [
          "Capacho Viejo",
          "Cipriano Castro",
          "Manuel Felipe Rugeles",
        ],
      },
      {
        municipio: "Libertador",
        parroquias: [
          "Abejales",
          "Don Emeterio Ochoa",
          "Doradas",
          "San Joaquín De Navay",
        ],
      },
      { municipio: "Lobatera", parroquias: ["Constitución", "Lobatera"] },
      { municipio: "Michelena", parroquias: ["Michelena"] },
      { municipio: "Panamericano", parroquias: ["Coloncito", "La Palmita"] },
      {
        municipio: "Pedro María Ureña",
        parroquias: ["Nueva Arcadia", "Ureña"],
      },
      { municipio: "Rafael Urdaneta", parroquias: ["Delicias"] },
      {
        municipio: "Samuel Darío Maldonado",
        parroquias: ["Boconó", "Hernández", "La Tendida"],
      },
      {
        municipio: "San Cristóbal",
        parroquias: [
          "Dr. Francisco Romero Lobo",
          "La Concordia",
          "Pedro María Morantes",
          "San Juan Bautista",
          "San Sebastián",
        ],
      },
      { municipio: "San Judas Tadeo", parroquias: ["Umuquena"] },
      { municipio: "Seboruco", parroquias: ["Seboruco"] },
      { municipio: "Simón Rodríguez", parroquias: ["San Simón"] },
      {
        municipio: "Sucre",
        parroquias: ["Eleazar López Contreras", "Queniquea", "San Pablo"],
      },
      { municipio: "Torbes", parroquias: ["San Josecito"] },
      {
        municipio: "Uribante",
        parroquias: ["Cárdenas", "Juan Pablo Peñaloza", "Potosí", "Pregonero"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Trujillo",
    municipios: [
      {
        municipio: "Andrés Bello",
        parroquias: ["Araguaney", "El Jagüito", "La Esperanza", "Santa Isabel"],
      },
      {
        municipio: "Boconó",
        parroquias: [
          "Ayacucho",
          "Boconó",
          "Burbusay",
          "El Carmen",
          "General Rivas",
          "Guaramacal",
          "Monseñor Jáuregui",
          "Mosquey",
          "Rafael Rangel",
          "San José",
          "San Miguel",
          "Vega De Guaramacal",
        ],
      },
      {
        municipio: "Bolívar",
        parroquias: ["Cheregüe", "Granados", "Sabana Grande"],
      },
      {
        municipio: "Candelaria",
        parroquias: [
          "Arnoldo Gabaldón",
          "Bolivia",
          "Carrillo",
          "Cegarra",
          "Chejendé",
          "Manuel Salvador Ulloa",
          "San José",
        ],
      },
      {
        municipio: "Carache",
        parroquias: [
          "Carache",
          "Cuicas",
          "La Concepción",
          "Panamericana",
          "Santa Cruz",
        ],
      },
      {
        municipio: "Escuque",
        parroquias: ["Escuque", "La Unión", "Sabana Libre", "Santa Rita"],
      },
      {
        municipio: "José Felipe Márquez Cañizales",
        parroquias: ["Antonio José De Sucre", "El Socorro", "Los Caprichos"],
      },
      {
        municipio: "Juan Vicente Campo Elías",
        parroquias: ["Arnoldo Gabaldón", "Campo Elías"],
      },
      {
        municipio: "La Ceiba",
        parroquias: [
          "El Progreso",
          "La Ceiba",
          "Santa Apolonia",
          "Tres De Febrero",
        ],
      },
      {
        municipio: "Miranda",
        parroquias: [
          "Agua Caliente",
          "Agua Santa",
          "El Cenizo",
          "El Dividive",
          "Valerita",
        ],
      },
      {
        municipio: "Monte Carmelo",
        parroquias: ["Buena Vista", "Monte Carmelo", "Santa María Del Horcón"],
      },
      { municipio: "Motatán", parroquias: ["El Baño", "Jalisco", "Motatán"] },
      {
        municipio: "Pampán",
        parroquias: ["Flor De Patria", "La Paz", "Pampán", "Santa Ana"],
      },
      {
        municipio: "Pampanito",
        parroquias: ["La Concepción", "Pampanito", "Pampanito II"],
      },
      {
        municipio: "Rafael Rangel",
        parroquias: [
          "Betijoque",
          "José Gregorio Hernández",
          "La Pueblita",
          "Los Cedros",
        ],
      },
      {
        municipio: "San Rafael De Carvajal",
        parroquias: [
          "Antonio Nicolás Briceño",
          "Campo Alegre",
          "Carvajal",
          "José Leonardo Suárez",
        ],
      },
      {
        municipio: "Sucre",
        parroquias: [
          "El Paraíso",
          "Junín",
          "Sabana De Mendoza",
          "Valmore Rodríguez",
        ],
      },
      {
        municipio: "Trujillo",
        parroquias: [
          "Andrés Linares",
          "Chiquinquirá",
          "Cristóbal Mendoza",
          "Cruz Carrillo",
          "Matriz",
          "Monseñor Carrillo",
          "Tres Esquinas",
        ],
      },
      {
        municipio: "Urdaneta",
        parroquias: [
          "Cabimbú",
          "Jajó",
          "La Mesa",
          "La Quebrada",
          "Santiago",
          "Tuñame",
        ],
      },
      {
        municipio: "Valera",
        parroquias: [
          "Juan Ignacio Montilla",
          "La Beatriz",
          "La Puerta",
          "Mendoza",
          "Mercedes Díaz",
          "San Luis",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Yaracuy",
    municipios: [
      { municipio: "Aristides Bastidas", parroquias: ["San Pablo"] },
      { municipio: "Bolívar", parroquias: ["Aroa"] },
      { municipio: "Bruzual", parroquias: ["Campo Elias", "Chivacoa"] },
      { municipio: "Cocorote", parroquias: ["Cocorote"] },
      { municipio: "Independencia", parroquias: ["Independencia"] },
      { municipio: "José Antonio Páez", parroquias: ["Sabana De Parra"] },
      { municipio: "La Trinidad", parroquias: ["Boraure"] },
      { municipio: "Manuel Monge", parroquias: ["Yumare"] },
      { municipio: "Nirgua", parroquias: ["Nirgua", "Salom", "Temerla"] },
      { municipio: "Peña", parroquias: ["San Andrés", "Yaritagua"] },
      {
        municipio: "San Felipe",
        parroquias: ["Albarico", "San Felipe", "San Javier"],
      },
      { municipio: "Sucre", parroquias: ["Guama"] },
      { municipio: "Urachiche", parroquias: ["Urachiche"] },
      { municipio: "Veroes", parroquias: ["El Guayabo", "Farriar"] },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Zulia",
    municipios: [
      {
        municipio: "Almirante Padilla",
        parroquias: ["Isla De Toas", "Monagas"],
      },
      {
        municipio: "Baralt",
        parroquias: [
          "General Urdaneta",
          "Libertador",
          "Manuel Guanipa Matos",
          "Marcelino Briceño",
          "Pueblo Nuevo",
          "San Timoteo",
        ],
      },
      {
        municipio: "Cabimas",
        parroquias: [
          "Ambrosio",
          "Aristides Calvani",
          "Carmen Herrera",
          "Germán Ríos Linares",
          "Jorge Hernández",
          "La Rosa",
          "Punta Gorda",
          "Rómulo Betancourt",
          "San Benito",
        ],
      },
      { municipio: "Catatumbo", parroquias: ["Encontrados", "Udón Pérez"] },
      {
        municipio: "Colon",
        parroquias: [
          "Moralito",
          "San Carlos Del Zulia",
          "Santa Bárbara",
          "Santa Cruz Del Zulia",
          "Urribari",
        ],
      },
      {
        municipio: "Francisco Javier Pulgar",
        parroquias: [
          "Agustín Codazzi",
          "Carlos Quevedo",
          "Francisco Javier Pulgar",
          "Simón Rodríguez",
        ],
      },
      {
        municipio: "Indigena Bolivariano Guajira",
        parroquias: [
          "Alta Guajira",
          "Elías Sánchez Rubio",
          "Guajira",
          "Sinamaica",
        ],
      },
      {
        municipio: "Jesús Enrique Lossada",
        parroquias: [
          "José Ramón Yepez",
          "La Concepción",
          "Mariano Parra León",
          "San José",
        ],
      },
      {
        municipio: "Jesús María Semprún",
        parroquias: ["Barí", "Jesús María Semprún"],
      },
      {
        municipio: "La Cañada De Urdaneta",
        parroquias: [
          "Andrés Bello",
          "Chiquinquirá",
          "Concepción",
          "El Carmelo",
          "Potreritos",
        ],
      },
      {
        municipio: "Lagunillas",
        parroquias: [
          "Alonso De Ojeda",
          "Campo Lara",
          "El Danto",
          "Eleazar López Contreras",
          "Libertad",
          "Venezuela",
        ],
      },
      {
        municipio: "Machiques De Perijá",
        parroquias: [
          "Bartolomé De Las Casas",
          "Libertad",
          "Río Negro",
          "San José De Perijá",
        ],
      },
      {
        municipio: "Mara",
        parroquias: [
          "La Sierrita",
          "Las Parcelas",
          "Luis De Vicente",
          "Monseñor Marcos Sergio Godoy",
          "Ricaurte",
          "San Rafael",
          "Tamare",
        ],
      },
      {
        municipio: "Maracaibo",
        parroquias: [
          "Antonio Borjas Romero",
          "Bolívar",
          "Cacique Mara",
          "Caracciolo Parra Perez",
          "Cecilio Acosta",
          "Chiquinquirá",
          "Coquivacoa",
          "Cristo De Aranza",
          "Francisco Eugenio Bustamante",
          "Idelfonzo Vásquez",
          "Juana De Ávila",
          "Luis Hurtado Higuera",
          "Manuel Dagnino",
          "Olegario Villalobos",
          "Raúl Leoni",
          "San Isidro",
          "Santa Lucía",
          "Venancio Pulgar",
        ],
      },
      {
        municipio: "Miranda",
        parroquias: [
          "Altagracia",
          "Ana María Campos",
          "Faría",
          "José Antonio Chaves",
          "San Antonio",
          "San José",
        ],
      },
      {
        municipio: "Rosario De Perijá",
        parroquias: ["Donaldo García", "El Rosario", "Sixto Zambrano"],
      },
      {
        municipio: "San Francisco",
        parroquias: [
          "Domitilia Flores",
          "El Bajo",
          "Francisco De Ochoa",
          "José Domingo Rus",
          "Los Cortijos",
          "Marcial Hernández",
          "San Francisco",
        ],
      },
      {
        municipio: "Santa Rita",
        parroquias: [
          "El Mene",
          "José Cenovio Urribarri",
          "Pedro Lucas Urribarri",
          "Santa Rita",
        ],
      },
      {
        municipio: "Simón Bolívar",
        parroquias: [
          "Manuel Manrique",
          "Rafel María Baralt",
          "Rafael Urdaneta",
        ],
      },
      {
        municipio: "Sucre",
        parroquias: [
          "Bobures",
          "El Batey",
          "Gibraltar",
          "Heras",
          "Monseñor Arturo Celestino Álvarez",
          "Rómulo Gallegos",
        ],
      },
      {
        municipio: "Valmore Rodríguez",
        parroquias: ["La Victoria", "Rafael Urdaneta", "Raúl Cuenca"],
      },
    ],
  },
];

module.exports = {
  parroquias,
};
