const parroquias = [
  {
    pais: "Venezuela",
    estado: "Amazonas",
    municipios: [
      {
        municipio: "Autónomo Alto Orinoco",
        parroquias: [
          "Alto Orinoco",
          "Huachamacare",
          "La Esmeralda - Alto Orinoco",
          "Marawaka",
          "Mavaca",
          "Sierra Parima",
        ],
      },
      {
        municipio: "Autónomo Atabapo",
        parroquias: ["Caname", "San Fernando De Atabapo", "Ucata", "Yapacana"],
      },
      {
        municipio: "Autónomo Atures",
        parroquias: [
          "Fernando Girón Tovar",
          "Luis Alberto Gómez",
          "Parhueña",
          "Platanillal",
        ],
      },
      {
        municipio: "Autónomo Autana",
        parroquias: [
          "Guayapo",
          "Isla Ratón",
          "Munduapo",
          "Samariapo",
          "Sipapo",
        ],
      },
      {
        municipio: "Autónomo Manapiare",
        parroquias: [
          "Alto Ventuari",
          "Bajo Ventuari",
          "Medio Ventuari",
          "San Juan De Manapiare",
        ],
      },
      {
        municipio: "Autónomo Maroa",
        parroquias: ["Comunidad", "Maroa", "Victorino"],
      },
      {
        municipio: "Autónomo Río Negro",
        parroquias: [
          "Casiquiare",
          "Cocuy",
          "San Carlos De Río Negro",
          "Solano",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Anzoátegui",
    municipios: [
      {
        municipio: "Anaco",
        parroquias: ["Anaco", "Buena Vista", "San Joaquín"],
      },
      { municipio: "Aragua", parroquias: ["Aragua", "Cachipo"] },
      {
        municipio: "Diego Bautista Urbaneja",
        parroquias: ["El Morro", "Lecherías"],
      },
      {
        municipio: "Fernando De Peñalver",
        parroquias: [
          "Puerto Píritu - Fernando De Peñalver",
          "San Miguel",
          "Sucre",
        ],
      },
      {
        municipio: "Francisco De Miranda",
        parroquias: [
          "Atapirire",
          "Boca Del Pao",
          "El Pao",
          "Pariaguán - Francisco De Miranda",
        ],
      },
      {
        municipio: "Francisco Del Carmen Carvajal",
        parroquias: ["Santa Bárbara", "Valle De Guanape"],
      },
      { municipio: "Guanta", parroquias: ["Chorrerón", "Guanta"] },
      {
        municipio: "Independencia",
        parroquias: ["La Soledad - Independencia", "Mamo"],
      },
      {
        municipio: "José Gregorio Monagas",
        parroquias: [
          "Mapire - José Gregorio Monagas",
          "Piar",
          "San Diego De Cabrutica",
          "Santa Clara",
          "Uverito",
          "Zuata",
        ],
      },
      {
        municipio: "Juan Antonio Sotillo",
        parroquias: ["Pozuelos", "Puerto La Cruz"],
      },
      { municipio: "Juan Manuel Cajigal", parroquias: ["Onoto", "San Pablo"] },
      {
        municipio: "Libertad",
        parroquias: ["El Carito", "San Mateo - Libertad", "Santa Inés"],
      },
      {
        municipio: "Manuel Ezequiel Bruzual",
        parroquias: ["Clarines", "Guanape", "Sabana De Uchire"],
      },
      {
        municipio: "Pedro María Freites",
        parroquias: [
          "Cantaura - Pedro María Freites",
          "Libertador",
          "Santa Rosa",
          "Urica",
        ],
      },
      { municipio: "Píritu", parroquias: ["Píritu", "San Francisco"] },
      { municipio: "San José De Guanipa", parroquias: ["San José De Guanipa"] },
      {
        municipio: "San Juan De Capistrano",
        parroquias: ["Boca De Chávez", "Boca Uchire"],
      },
      { municipio: "Santa Ana", parroquias: ["Pueblo Nuevo", "Santa Ana"] },
      {
        municipio: "Simón Bolívar",
        parroquias: [
          "Bergantin",
          "Caigua",
          "El Carmen",
          "El Pilar",
          "Naricual",
          "San Cristobal",
        ],
      },
      {
        municipio: "Simón Rodríguez",
        parroquias: ["Edmundo Barrios", "Miguel Otero Silva"],
      },
      {
        municipio: "Sir Arthur Mc Gregor",
        parroquias: ["El Chaparro", "Tomás Alfaro Calatrava"],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Apure",
    municipios: [
      {
        municipio: "Achaguas",
        parroquias: [
          "Achaguas",
          "Apurito",
          "El Yagual",
          "Guachara",
          "Mucuritas",
          "Queseras Del Medio",
        ],
      },
      { municipio: "Biruaca", parroquias: ["Biruaca"] },
      {
        municipio: "Muñoz",
        parroquias: [
          "Bruzual",
          "Mantecal",
          "Quintero",
          "Rincón Hondo",
          "San Vicente",
        ],
      },
      {
        municipio: "Páez",
        parroquias: [
          "Aramendi",
          "El Amparo",
          "Guasdualito",
          "San Camilo",
          "Urdaneta",
        ],
      },
      {
        municipio: "Pedro Camejo",
        parroquias: ["Codazzi", "Cunaviche", "San Juan De Payara"],
      },
      { municipio: "Rómulo Gallegos", parroquias: ["Elorza", "La Trinidad"] },
      {
        municipio: "San Fernando",
        parroquias: [
          "El Recreo",
          "Peñalver",
          "San Fernando",
          "San Rafael De Atamaica",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Aragua",
    municipios: [
      { municipio: "Bolívar", parroquias: ["San Mateo - Bolívar"] },
      { municipio: "Camatagua", parroquias: ["Camatagua", "Carmen De Cura"] },
      {
        municipio: "Francisco Linares Alcántara",
        parroquias: [
          "Francisco De Miranda",
          "Monseñor Feliciano González - Paraparal",
          "Santa Rita - Francisco Linares Alcántara",
        ],
      },
      {
        municipio: "Girardot",
        parroquias: [
          "Andrés Eloy Blanco",
          "Choroní",
          "Joaquín Crespo",
          "José Casanova Godoy",
          "Las Delicias",
          "Los Tacariguas",
          "Madre María De San José",
          "Pedro José Ovalles",
        ],
      },
      { municipio: "José Ángel Lamas", parroquias: ["Capital Santa Cruz"] },
      {
        municipio: "José Félix Rivas",
        parroquias: [
          "Castor Nieves Ríos",
          "La Victoria - Juan Vicente Bolívar",
          "Las Guacamayas",
          "Pao De Zárate",
          "Zuata",
        ],
      },
      { municipio: "José Rafael Revenga", parroquias: ["El Consejo"] },
      {
        municipio: "Libertador",
        parroquias: ["Palo Negro - Libertador", "San Martín De Porres"],
      },
      {
        municipio: "Mario Briceño Iragorry",
        parroquias: ["Caña De Azúcar", "El Limón - Mario Briceño Iragorry"],
      },
      {
        municipio: "Ocumare De La Costa De Oro",
        parroquias: ["Ocumare De La Costa"],
      },
      {
        municipio: "San Casimiro",
        parroquias: [
          "Güiripa",
          "Ollas De Caramacate",
          "San Casimiro",
          "Valle Morín",
        ],
      },
      { municipio: "San Sebastián", parroquias: ["San Sebastián"] },
      {
        municipio: "Santiago Mariño",
        parroquias: [
          "Alfredo Pacheco Miranda",
          "Arévalo Aponte",
          "Chuao",
          "Samán De Güere",
          "Turmero - Santiago Mariño",
        ],
      },
      {
        municipio: "Santos Michelena",
        parroquias: ["Las Tejerías - Santos Michelena", "Tiara"],
      },
      { municipio: "Sucre", parroquias: ["Bella Vista", "Cagua - Sucre"] },
      { municipio: "Tovar", parroquias: ["Colonia Tovar"] },
      {
        municipio: "Urdaneta",
        parroquias: [
          "Barbacoas - Urdaneta",
          "Las Peñitas",
          "San Francisco De Cara",
          "Taguay",
        ],
      },
      {
        municipio: "Zamora",
        parroquias: [
          "Augusto Mijares",
          "Magdaleno",
          "San Francisco De Asís",
          "Valles De Tucutunemo - Los Bagres",
          "Villa De Cura - Zamora",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Barinas",
    municipios: [
      {
        municipio: "Alberto Arvelo Torrealba",
        parroquias: ["Rodríguez Domínguez", "Sabaneta"],
      },
      {
        municipio: "Andrés Eloy Blanco",
        parroquias: ["El Cantón", "Puerto Vivas", "Santa Cruz De Guacas"],
      },
      {
        municipio: "Antonio José De Sucre",
        parroquias: ["Andrés Bello", "Nicolás Pulido", "Ticoporo"],
      },
      {
        municipio: "Arismendi",
        parroquias: ["Arismendi", "Guadarrama", "La Unión", "San Antonio"],
      },
      {
        municipio: "Barinas",
        parroquias: [
          "Alfredo Arvelo Larriva",
          "Alto Barinas",
          "Barinas",
          "Corazón De Jesús",
          "Dominga Ortiz De Páez",
          "El Carmen",
          "Juan Antonio Rodríguez Domínguez",
          "Manuel Palacio Fajardo",
          "Ramón Ignacio Méndez",
          "Rómulo Betancourt",
          "San Silvestre",
          "Santa Inés",
          "Santa Lucía",
          "Torunos",
        ],
      },
      {
        municipio: "Bolívar",
        parroquias: ["Altamira", "Barinitas", "Calderas"],
      },
      {
        municipio: "Cruz Paredes",
        parroquias: ["Barrancas", "El Socorro", "Masparrito"],
      },
      {
        municipio: "Ezequiel Zamora",
        parroquias: [
          "José Ignacio Del Pumar",
          "Pedro Briceño Méndez",
          "Ramón Ignacio Méndez",
          "Santa Bárbara",
        ],
      },
      {
        municipio: "Obispos",
        parroquias: ["El Real", "La Luz", "Los Guasimitos", "Obispos"],
      },
      {
        municipio: "Pedraza",
        parroquias: [
          "Ciudad Bolivia",
          "Ignacio Briceño",
          "José Félix Ribas",
          "Páez",
        ],
      },
      {
        municipio: "Rojas",
        parroquias: [
          "Dolores",
          "Libertad",
          "Palacio Fajardo",
          "Santa Rosa",
          "Simón Rodríguez",
        ],
      },
      {
        municipio: "Sosa",
        parroquias: [
          "Ciudad De Nutrias",
          "El Regalo",
          "Puerto De Nutrias",
          "Santa Catalina",
          "Simón Bolívar",
        ],
      },
    ],
  },
  {
    pais: "Venezuela",
    estado: "Bolívar",
    municipios: [
      "Bolivariano Angostura",
      "Caroní",
      "Cedeño",
      "El Callao",
      "Gran Sabana",
      "Heres",
      "Padre Pedro Chien",
      "Piar",
      "Roscio",
      "Sifontes",
      "Sucre",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Miranda",
    municipios: [
      "Acevedo",
      "Andrés Bello",
      "Baruta",
      "Bolivariano Guaicaipuro",
      "Brión",
      "Buroz",
      "Carrizal",
      "Chacao",
      "Cristobal Rojas",
      "El Hatillo",
      "Independencia",
      "Lander",
      "Los Salias",
      "Páez",
      "Paz Castillo",
      "Pedro Gual",
      "Plaza",
      "Simón Bolívar",
      "Sucre",
      "Urdaneta",
      "Zamora",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Carabobo",
    municipios: [
      "Bejuma",
      "Carlos Arvelo",
      "Diego Ibarra",
      "Guacara",
      "Juan José Mora",
      "Libertador",
      "Los Guayos",
      "Miranda",
      "Montalban",
      "Naguanagua",
      "Puerto Cabello",
      "San Diego",
      "San Joaquín",
      "Valencia",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Cojedes",
    municipios: [
      "Anzoátegui",
      "El Pao",
      "Ezequiel Zamora",
      "Girardot",
      "Lima Blanco",
      "Ricaurte",
      "Romulo Gallegos",
      "Tinaco",
      "Tinaquillo",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Delta Amacuro",
    municipios: ["Antonio Diaz", "Casacoima", "Pedernales", "Tucupita"],
  },
  {
    pais: "Venezuela",
    estado: "Dependencias Federales",
    municipios: [
      "Archipiélago Los Roques",
      "La Blanquilla",
      "La Orchila",
      "La Tortuga",
      "Las Aves",
      "Los Frailes",
      "Los Hermanos",
      "Los Testigos",
      "Territorio Nacional",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Distrito Capital",
    municipios: ["Bolivariano Libertador"],
  },
  {
    pais: "Venezuela",
    estado: "Falcón",
    municipios: [
      "Acosta",
      "Bolívar",
      "Buchivacoa",
      "Cacique Manaure",
      "Carirubana",
      "Colina",
      "Dabajuro",
      "Democracia",
      "Falcón",
      "Federación",
      "Jacura",
      "Los Taques",
      "Mauroa",
      "Miranda",
      "Monseñor Iturriza",
      "Palmasola",
      "Petit",
      "Píritu",
      "San Francisco",
      "Silva",
      "Sucre",
      "Tocópero",
      "Unión",
      "Urumaco",
      "Zamora",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Guárico",
    municipios: [
      "Autónomo José Tadeo Monagas",
      "Camaguán",
      "Chaguaramas",
      "El Socorro",
      "Francisco De Miranda",
      "José Felix Ribas",
      "Juan Germán Roscio",
      "Juan José Rondón",
      "Julián Mellado",
      "Leonardo Infante",
      "Ortiz",
      "Pedro Zaraza",
      "San Gerónimo De Guayabal",
      "San José De Guaribe",
      "Santa María De Ipire",
    ],
  },
  { pais: "Venezuela", estado: "La Guaira", municipios: ["Vargas"] },
  {
    pais: "Venezuela",
    estado: "Lara",
    municipios: [
      "Andrés Eloy Blanco",
      "Crespo",
      "Iribarren",
      "Jiménez",
      "Morán",
      "Palavecino",
      "Simón Planas",
      "Torres",
      "Urdaneta",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Mérida",
    municipios: [
      "Alberto Adriani",
      "Andrés Bello",
      "Antonio Pinto Salinas",
      "Aricagua",
      "Arzobispo Chacón",
      "Campo Elías",
      "Caracciolo Parra Olmedo",
      "Cardenal Quintero",
      "Guaraque",
      "Julio César Salas",
      "Justo Briceño",
      "Libertador",
      "Miranda",
      "Obispo Ramos De Lora",
      "Padre Noguera",
      "Pueblo Llano",
      "Rangel",
      "Rivas Dávila",
      "Santos Marquina",
      "Sucre",
      "Tovar",
      "Tulio Febres Cordero",
      "Zea",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Monagas",
    municipios: [
      "Acosta",
      "Aguasay",
      "Bolívar",
      "Caripe",
      "Cedeño",
      "Ezequiel Zamora",
      "Libertador",
      "Maturín",
      "Piar",
      "Punceres",
      "Santa Bárbara",
      "Sotillo",
      "Uracoa",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Nueva Esparta",
    municipios: [
      "Antolín Del Campo",
      "Arismendi",
      "Díaz",
      "García",
      "Gómez",
      "Maneiro",
      "Marcano",
      "Mariño",
      "Península De Macanao",
      "Tubores",
      "Villalba",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Portuguesa",
    municipios: [
      "Agua Blanca",
      "Araure",
      "Esteller",
      "Guanare",
      "Guanarito",
      "Monseñor José Vicente De Unda",
      "Ospino",
      "Páez",
      "Papelón",
      "San Genaro De Boconoito",
      "San Rafael De Onoto",
      "Santa Rosalía",
      "Sucre",
      "Turén",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Sucre",
    municipios: [
      "Andrés Eloy Blanco",
      "Andrés Mata",
      "Arismendi",
      "Benítez",
      "Bermúdez",
      "Bolívar",
      "Cajigal",
      "Cruz Salmerón Acosta",
      "Libertador",
      "Mariño",
      "Mejía",
      "Montes",
      "Ribero",
      "Sucre",
      "Valdez",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Táchira",
    municipios: [
      "Andrés Bello",
      "Antonio Rómulo Costa",
      "Ayacucho",
      "Bolívar",
      "Cárdenas",
      "Cordoba",
      "Fernández Feo",
      "Francisco De Miranda",
      "García De Hevia",
      "Guásimos",
      "Independencia",
      "Jáuregui",
      "José María Vargas",
      "Junín",
      "Libertad",
      "Libertador",
      "Lobatera",
      "Michelena",
      "Panamericano",
      "Pedro María Ureña",
      "Rafael Urdaneta",
      "Samuel Darío Maldonado",
      "San Cristóbal",
      "San Judas Tadeo",
      "Seboruco",
      "Simón Rodríguez",
      "Sucre",
      "Torbes",
      "Uribante",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Trujillo",
    municipios: [
      "Andrés Bello",
      "Boconó",
      "Bolívar",
      "Candelaria",
      "Carache",
      "Escuque",
      "José Felipe Márquez Cañizales",
      "Juan Vicente Campo Elías",
      "La Ceiba",
      "Miranda",
      "Monte Carmelo",
      "Motatán",
      "Pampán",
      "Pampanito",
      "Rafael Rangel",
      "San Rafael De Carvajal",
      "Sucre",
      "Trujillo",
      "Urdaneta",
      "Valera",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Yaracuy",
    municipios: [
      "Aristides Bastidas",
      "Bolívar",
      "Bruzual",
      "Cocorote",
      "Independencia",
      "José Antonio Páez",
      "La Trinidad",
      "Manuel Monge",
      "Nirgua",
      "Peña",
      "San Felipe",
      "Sucre",
      "Urachiche",
      "Veroes",
    ],
  },
  {
    pais: "Venezuela",
    estado: "Zulia",
    municipios: [
      "Almirante Padilla",
      "Baralt",
      "Cabimas",
      "Catatumbo",
      "Colon",
      "Francisco Javier Pulgar",
      "Indigena Bolivariano Guajira",
      "Jesús Enrique Lossada",
      "Jesús María Semprún",
      "La Cañada De Urdaneta",
      "Lagunillas",
      "Machiques De Perijá",
      "Mara",
      "Maracaibo",
      "Miranda",
      "Rosario De Perijá",
      "San Francisco",
      "Santa Rita",
      "Simón Bolívar",
      "Sucre",
      "Valmore Rodríguez",
    ],
  },
];

module.exports = {
  parroquias,
};
